# Generated by Django 6.0.3 on 2026-06-01 04:43

import agent.models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import scene.mixins
import task.mixins
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '__first__'),
        ('filer', '0018_alter_file_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('global_default', models.BooleanField(default=False, verbose_name='global default')),
            ],
            bases=(models.Model, agent.models.GetContentsMixin, scene.mixins.ModelDisplayMixin),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Game', max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Action', max_length=200, verbose_name='name')),
                ('is_intro', models.SlugField(blank=True, choices=[('scene', 'Scene Intro'), ('story', 'Story Intro')], null=True, verbose_name='is intro')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('prompt_video', models.TextField(blank=True, null=True, verbose_name='prompt video')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True, verbose_name='action')),
                ('prompt_comic', models.TextField(blank=True, null=True, verbose_name='prompt comic')),
                ('prompt_voice', models.TextField(blank=True, null=True, verbose_name='prompt voice')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('audio_voice', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file', verbose_name='audio voice')),
                ('consistent_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistent_actions', to='scene.action', verbose_name='consistent with')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('image_comic', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic')),
                ('image_first', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_first', to=settings.FILER_IMAGE_MODEL, verbose_name='image first')),
                ('image_last', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_last', to=settings.FILER_IMAGE_MODEL, verbose_name='image last')),
                ('image_refine', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_refine', to=settings.FILER_IMAGE_MODEL, verbose_name='image refine')),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_video', to='filer.file', verbose_name='video')),
            ],
            options={
                'ordering': ['-order', 'name'],
            },
            bases=(task.mixins.AfterSaveActionMixin, models.Model, agent.models.GetContentsMixin, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.CreateModel(
            name='ActionOrganizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.CreateModel(
            name='ComicAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.CreateModel(
            name='VideoAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.CreateModel(
            name='VoiceAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            bases=(models.Model, scene.mixins.UserCreatorMixin),
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True, verbose_name='action')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backgrounds', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('image_refine', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_refine', to=settings.FILER_IMAGE_MODEL, verbose_name='image refine')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
            bases=(task.mixins.AfterSaveActionMixin, models.Model, agent.models.GetContentsMixin, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.AddField(
            model_name='action',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='scene.background', verbose_name='background'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True, verbose_name='action')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
            bases=(models.Model, agent.models.GetContentsMixin, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.AddField(
            model_name='action',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='scene.character', verbose_name='actor'),
        ),
        migrations.AddField(
            model_name='action',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='actions_cast', to='scene.character', verbose_name='cast'),
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True, verbose_name='action')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='props', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            bases=(task.mixins.AfterSaveActionMixin, models.Model, agent.models.GetContentsMixin, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.AddField(
            model_name='action',
            name='props',
            field=models.ManyToManyField(blank=True, related_name='actions', to='scene.prop', verbose_name='props'),
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('render_type', models.CharField(choices=[('film', 'Film'), ('comic', 'Graphic Novel'), ('animatic', 'Animatic')], default='film', help_text='The format in which this scene will be synthesized.', max_length=50, verbose_name='render type')),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_videos', to='filer.file', verbose_name='video')),
            ],
            options={
                'verbose_name': 'Render Composition',
                'verbose_name_plural': 'Render Compositions',
            },
            bases=(scene.mixins.RenderTypeMixin, models.Model, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('prompt', models.TextField(blank=True, default='#Location\n#Cast\n#Props\n#Actions\n', null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True, verbose_name='action')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scene.author', verbose_name='author')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=(task.mixins.AfterSaveActionMixin, models.Model, task.models.TaskHolder, agent.models.GetContentsMixin, scene.mixins.ModelDisplayMixin),
        ),
        migrations.CreateModel(
            name='RenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='config')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_items', to='scene.action', verbose_name='action')),
                ('audio', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item_audio', to='filer.file', verbose_name='audio')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('render', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='render_items', to='scene.render', verbose_name='render')),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item_video', to='filer.file', verbose_name='video')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_items', to='scene.scene', verbose_name='scene')),
            ],
            options={
                'verbose_name': 'Render Item',
                'verbose_name_plural': 'Render Items',
                'ordering': ['order'],
            },
            bases=(models.Model, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.AddField(
            model_name='render',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='scene.scene', verbose_name='scene'),
        ),
        migrations.AddField(
            model_name='action',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scene.scene', verbose_name='scene'),
        ),
        migrations.CreateModel(
            name='SceneOrganizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.scene',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('prompt', models.TextField(blank=True, default='#Plot\n', null=True, verbose_name='prompt')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True, verbose_name='action')),
                ('render_type', models.CharField(choices=[('film', 'Film'), ('comic', 'Graphic Novel'), ('animatic', 'Animatic')], default='animatic', help_text='The default render format for this story.', max_length=50, verbose_name='render type')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors_stories', to='agent.agent', verbose_name='mentor')),
            ],
            bases=(task.mixins.AfterSaveActionMixin, scene.mixins.RenderTypeMixin, models.Model, agent.models.GetContentsMixin, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scene.story', verbose_name='story'),
        ),
        migrations.AddField(
            model_name='render',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='scene.story', verbose_name='story'),
        ),
        migrations.AddField(
            model_name='prop',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='scene.story', verbose_name='story'),
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message to include in the nudge email.', null=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_nudges', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_nudges', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='scene.story', verbose_name='story')),
            ],
            bases=(models.Model, scene.mixins.EmailSenderMixin),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scene.story', verbose_name='story'),
        ),
        migrations.AddField(
            model_name='background',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='scene.story', verbose_name='story'),
        ),
        migrations.AddField(
            model_name='author',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='scene.story', verbose_name='story'),
        ),
        migrations.CreateModel(
            name='StoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_groups', to='scene.story', verbose_name='story')),
                ('users', models.ManyToManyField(related_name='story_groups', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto create authors from this group, it happens only when the script is saved for the first time', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='scene.storygroup', verbose_name='group'),
        ),
        migrations.CreateModel(
            name='StoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_filters', models.BooleanField(default=True, verbose_name='enable filters')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_profiles', to='scene.storygroup', verbose_name='group')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_profiles', to='scene.scene', verbose_name='scene')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_profiles', to='scene.story', verbose_name='story')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='scene.style', verbose_name='style'),
        ),
        migrations.AddField(
            model_name='story',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.theme', verbose_name='theme'),
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, default='Style: [describe the style of speaking you want, e.g. excited, sad, professional, etc.]\nPace: [describe the pace of speaking you want, e.g. fast, slow, etc.]\nAccent: [describe the accent you want, e.g. British, American, etc.]\n\n', null=True, verbose_name='prompt')),
                ('sample_text', models.TextField(blank=True, default='Hello, this is a sample voice. 1, 2, 3. Change me and add a sample prompt for better results. Add audio effects for more interesting voices!', null=True, verbose_name='sample text')),
                ('global_default', models.BooleanField(default=False, verbose_name='global default')),
                ('action', models.SlugField(blank=True, choices=[('generate_voice', 'Generate Voice')], null=True, verbose_name='action')),
                ('audio_voice', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='filer.file', verbose_name='audio voice')),
                ('google_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='agent.googlevoice', verbose_name='google voice')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='scene.story', verbose_name='story')),
            ],
            bases=(task.mixins.AfterSaveActionMixin, models.Model, task.models.TaskHolder, agent.models.GetContentsMixin, scene.mixins.ModelDisplayMixin),
        ),
        migrations.AddField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='scene.voice', verbose_name='voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_voice', to='scene.voice', verbose_name='voice'),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('contribuition', models.TextField(blank=True, choices=[('pay', 'I am ok to pay 20/30 dollars/euros for the workshop'), ('api_key', 'I am ok to bring my google api key to the project'), ('collaborate', 'I want to collaborate in another way'), ('trial', 'I just want to try it out and use the local open source version')], null=True, verbose_name='contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('prompt', models.TextField(blank=True, default='#Location\n#Cast\n#Props\n#Actions\n', help_text='Just imagine and write with as many typos as you want. Guillermo will curate your scene', null=True, verbose_name='A glimpse of your imagination')),
                ('group_number', models.IntegerField(blank=True, help_text='How many friends and family member you would bring to the workshop?', null=True, verbose_name='group number')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='scene.workshop', verbose_name='workshop')),
            ],
        ),
    ]
