# Generated by Django 5.2.10 on 2026-02-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='props',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='first',
            new_name='first_frame',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='last',
            new_name='last_frame',
        ),
        migrations.DeleteModel(
            name='Prop',
        ),
    ]
