# Generated by Django 6.0.3 on 2026-06-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='contribuition',
            field=models.TextField(blank=True, choices=[('pay', 'I am ok to pay 20/30 dollars/euros for the workshop'), ('api_key', 'I am ok to bring my google api key to the project'), ('collaborate', 'I want to help testing'), ('trial', 'I just want to try it out and use the local open source version')], null=True, verbose_name='contribution'),
        ),
        migrations.AlterField(
            model_name='storyprofile',
            name='enable_filters',
            field=models.BooleanField(default=False, verbose_name='enable filters'),
        ),
    ]
