# Generated by Django 5.2.10 on 2026-02-08 10:30

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_remove_action_props_rename_first_action_first_frame_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('plot', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RenameField(
            model_name='action',
            old_name='first_frame',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='last_frame',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='prompt_background',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='actioncharacter',
            old_name='prompt_text',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='action',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='action',
            name='prompt_foreground',
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expressions', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actioncharacter',
            name='expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_characters', to='scene.expression'),
        ),
    ]
