# Generated by Django 6.0.3 on 2026-06-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_alter_contactrequest_contribuition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderitem',
            name='params',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='params'),
        ),
    ]
