# Generated by Django 6.0.3 on 2026-06-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0002_alter_character_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scene.story', verbose_name='story'),
        ),
    ]
