# Generated by Django 5.2.10 on 2026-02-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0003_story_rename_first_frame_action_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='panel',
            new_name='image',
        ),
    ]
