# Generated by Django 6.0.3 on 2026-06-06 14:10

import django.db.models.deletion
import filer.fields.file
import scene.mixins
import task.mixins
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0003_renderitem_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='background',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='character',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='story',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action'),
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_file_in', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncs_in', to='filer.file', verbose_name='last file in')),
                ('last_file_out', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncs_out', to='filer.file', verbose_name='last file out')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='scene.story', verbose_name='story')),
            ],
            bases=(task.mixins.AfterSaveActionMixin, models.Model, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=10, verbose_name='type')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import')], null=True, verbose_name='action')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scene.sync', verbose_name='sync')),
                ('zip_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_items', to='filer.file', verbose_name='zip file')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(task.mixins.AfterSaveActionMixin, models.Model, task.models.TaskHolder, scene.mixins.ModelDisplayMixin),
        ),
    ]
