# Generated by Django 5.2.10 on 2026-02-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0004_rename_panel_action_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncharacter',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='actions_extras', to='scene.actioncharacter'),
        ),
        migrations.AddField(
            model_name='action',
            name='leading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_leading', to='scene.actioncharacter'),
        ),
    ]
