# Generated by Django 6.0.3 on 2026-06-11 17:00

import agent.models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import scene.mixins
import task.mixins
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0005_alter_action_action_alter_background_action_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionorganizer',
            options={'proxy': True},
        ),
        migrations.AlterModelOptions(
            name='comicaction',
            options={'proxy': True},
        ),
        migrations.AlterModelOptions(
            name='videoaction',
            options={'proxy': True},
        ),
        migrations.AlterModelOptions(
            name='voiceaction',
            options={'proxy': True},
        ),
        migrations.RenameModel(
            old_name='Action',
            new_name='Shot',
        ),
        migrations.AlterField(
            model_name='renderitem',
            name='shot',
            field=models.ForeignKey(on_delete=models.CASCADE, to='scene.shot'), # Adjust constraints as needed
        ),
    ]
