# Generated by Django 5.2.10 on 2026-02-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_remove_actioncharacter_action_action_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scene.expression'),
        ),
    ]
