# Generated by Django 6.0.3 on 2026-06-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0005_alter_action_action_alter_background_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Shot', 'verbose_name_plural': 'Shots'},
        ),
        migrations.AlterModelOptions(
            name='actionorganizer',
            options={'verbose_name': 'Shot Organizer', 'verbose_name_plural': 'Shot Organizers'},
        ),
        migrations.AlterModelOptions(
            name='comicaction',
            options={'verbose_name': 'Comic Shot', 'verbose_name_plural': 'Comic Shots'},
        ),
        migrations.AlterModelOptions(
            name='sceneorganizer',
            options={'verbose_name': 'Scene Organizer', 'verbose_name_plural': 'Scene Organizers'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='videoaction',
            options={'verbose_name': 'Video Shot ', 'verbose_name_plural': 'Video Shots'},
        ),
        migrations.AlterModelOptions(
            name='voiceaction',
            options={'verbose_name': 'Voice Shot', 'verbose_name_plural': 'Voice Shots'},
        ),
        migrations.AddField(
            model_name='action',
            name='configuration',
            field=models.JSONField(blank=True, null=True, verbose_name='configuration'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='prompt',
            field=models.TextField(blank=True, default='#Shots\n', null=True, verbose_name='prompt'),
        ),
    ]
