# Generated by Django 5.2.10 on 2026-02-15 11:49

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0006_character_expression'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncharacter',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_characters', to='scene.background'),
        ),
        migrations.AddField(
            model_name='actioncharacter',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_characters', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
