# Generated by Django 6.0.3 on 2026-06-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0006_alter_action_options_alter_actionorganizer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='configuration',
            new_name='parameters',
        ),
        migrations.AddField(
            model_name='action',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('voice', 'Voice'), ('video', 'Video'), ('comic', 'Comic'), ('video_loop', 'Video Loop')], max_length=20, null=True, verbose_name='shot type'),
        ),
    ]
