# Generated by Django 6.0.3 on 2026-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_prompt_is_global_prompt_order'),
        ('scene', '0007_rename_configuration_action_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='instructions',
            field=models.ManyToManyField(blank=True, null=True, to='agent.prompt', verbose_name='instructions'),
        ),
        migrations.AlterField(
            model_name='action',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('silent', 'Silent'), ('voice', 'Voice'), ('video', 'Video'), ('comic', 'Comic'), ('video_loop', 'Video Loop')], max_length=20, null=True, verbose_name='shot type'),
        ),
    ]
