# Generated by Django 5.2.10 on 2026-02-15 12:55

import agent.models
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0007_actioncharacter_background_actioncharacter_image'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='styles', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=(models.Model, agent.models.GetContentsMixin),
        ),
        migrations.AddField(
            model_name='action',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scene.style'),
        ),
        migrations.AddField(
            model_name='character',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scene.style'),
        ),
    ]
