# Generated by Django 5.2.10 on 2026-02-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0008_style_action_style_character_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='style',
        ),
        migrations.RemoveField(
            model_name='actioncharacter',
            name='background',
        ),
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
        migrations.AddField(
            model_name='background',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='scene.style'),
        ),
    ]
