# Generated by Django 6.0.3 on 2026-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0008_scene_instructions_alter_action_shot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='background',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='character',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='story',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='syncitem',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action'),
        ),
    ]
