# Generated by Django 5.2.10 on 2026-02-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0009_remove_action_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='leading',
        ),
        migrations.AddField(
            model_name='action',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_leading', to='scene.character'),
        ),
        migrations.AddField(
            model_name='scene',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='actions_extras', to='scene.character'),
        ),
    ]
