# Generated by Django 5.2.10 on 2026-02-16 17:28

import agent.models
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0010_remove_action_leading_action_actor_scene_plot_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-order']},
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='props', to=settings.FILER_IMAGE_MODEL)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='scene.style')),
            ],
            bases=(models.Model, agent.models.GetContentsMixin),
        ),
    ]
