# Generated by Django 6.0.3 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0010_alter_action_shot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='shot_type',
            field=models.CharField(blank=True, choices=[('silent', 'Silent'), ('voice', 'Voice'), ('video', 'Video'), ('comic', 'Comic'), ('video_loop', 'Video Loop')], max_length=20, null=True, verbose_name='shot type'),
        ),
    ]
