# Generated by Django 5.2.10 on 2026-02-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0011_alter_action_options_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='main_prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_main', to='scene.prop'),
        ),
        migrations.AddField(
            model_name='action',
            name='props',
            field=models.ManyToManyField(blank=True, related_name='actions', to='scene.prop'),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='scene.character'),
        ),
    ]
