# Generated by Django 5.2.10 on 2026-02-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0012_action_main_prop_action_props_alter_action_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='main_prop',
        ),
    ]
