# Generated by Django 5.2.10 on 2026-03-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0014_remove_action_text_comicaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='first',
        ),
        migrations.RemoveField(
            model_name='action',
            name='last',
        ),
    ]
