# Generated by Django 5.2.10 on 2026-03-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0015_remove_action_first_remove_action_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='consistent_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistent_actions', to='scene.action'),
        ),
        migrations.DeleteModel(
            name='ComicAction',
        ),
    ]
