# Generated by Django 5.2.10 on 2026-03-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0016_action_consistent_with_delete_comicaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scene.style'),
        ),
        migrations.DeleteModel(
            name='ActionCharacter',
        ),
    ]
