# Generated by Django 5.2.10 on 2026-03-11 10:34

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0017_scene_style_delete_actioncharacter'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefineAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.AddField(
            model_name='action',
            name='image_refine',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_refine', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_refine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
