# Generated by Django 5.2.10 on 2026-03-11 13:47

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0018_refineaction_action_image_refine_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='image_first',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_first', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='image_last',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_last', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='video',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_video', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
