# Generated by Django 5.2.10 on 2026-03-11 16:21

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0019_action_image_first_action_image_last_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.AlterField(
            model_name='action',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_video', to='filer.file'),
        ),
    ]
