# Generated by Django 5.2.10 on 2026-03-13 10:02

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0020_videoaction_alter_action_video'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='image_refine',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_refine', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='background',
            name='prompt_refine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='image_refine',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_refine', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='prompt_refine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prop',
            name='image_refine',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_refine', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='prop',
            name='prompt_refine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
