# Generated by Django 5.2.10 on 2026-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0021_background_image_refine_background_prompt_refine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Generate Video First Last')], null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Generate Video First Last')], null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Generate Video First Last')], null=True),
        ),
        migrations.AddField(
            model_name='prop',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Generate Video First Last')], null=True),
        ),
    ]
