# Generated by Django 5.2.10 on 2026-03-19 20:48

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0022_delete_story_action_exec_on_save_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-order', 'name']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='image_refine',
        ),
        migrations.AddField(
            model_name='action',
            name='image_comic',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_comic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
