# Generated by Django 5.2.10 on 2026-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0023_delete_story_comicaction_alter_action_options_and_more'),
    ]

    operations = [
    ]
