# Generated by Django 6.0.3 on 2026-08-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0023_remove_historicalscene_prompt_draft_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalVoice',
        ),
    ]
