# Generated by Django 5.2.10 on 2026-03-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0024_delete_story_action_exec_on_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic')], null=True),
        ),
    ]
