# Generated by Django 6.0.3 on 2026-08-19 10:19

import django.db.models.deletion
import filer.fields.file
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_messagepart_content_type_messagepart_object_id_and_more'),
        ('filer', '0018_alter_file_options'),
        ('scene', '0024_delete_historicalvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, default='Style: [describe the style of speaking you want, e.g. excited, sad, professional, etc.]\nPace: [describe the pace of speaking you want, e.g. fast, slow, etc.]\nAccent: [describe the accent you want, e.g. British, American, etc.]\n\n', null=True, verbose_name='prompt')),
                ('sample_text', models.TextField(blank=True, default='Hello, this is a sample voice. 1, 2, 3. Change me and add a sample prompt for better results. Add audio effects for more interesting voices!', null=True, verbose_name='sample text')),
                ('global_default', models.BooleanField(default=False, verbose_name='global default')),
                ('action', models.SlugField(blank=True, choices=[('generate_voice', 'Generate Voice')], null=True, verbose_name='action')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('audio_voice', filer.fields.file.FilerFileField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.file', verbose_name='audio voice')),
                ('google_voice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.googlevoice', verbose_name='google voice')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.story', verbose_name='story')),
            ],
            options={
                'verbose_name': 'historical voice',
                'verbose_name_plural': 'historical voices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
