# Generated by Django 6.0.3 on 2026-08-21 01:03

import django.db.models.deletion
import filer.fields.file
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0025_historicalvoice'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='audio_voice_en',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file', verbose_name='audio voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='audio_voice_es',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file', verbose_name='audio voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='audio_voice_fr',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file', verbose_name='audio voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='audio_voice_it',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file', verbose_name='audio voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='audio_voice_pt',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file', verbose_name='audio voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_comic_en',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_comic_es',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_comic_fr',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_comic_it',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='image_comic_pt',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_comic', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_comic_en',
            field=models.TextField(blank=True, null=True, verbose_name='prompt comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_comic_es',
            field=models.TextField(blank=True, null=True, verbose_name='prompt comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_comic_fr',
            field=models.TextField(blank=True, null=True, verbose_name='prompt comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_comic_it',
            field=models.TextField(blank=True, null=True, verbose_name='prompt comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_comic_pt',
            field=models.TextField(blank=True, null=True, verbose_name='prompt comic'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_voice_en',
            field=models.TextField(blank=True, null=True, verbose_name='prompt voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_voice_es',
            field=models.TextField(blank=True, null=True, verbose_name='prompt voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_voice_fr',
            field=models.TextField(blank=True, null=True, verbose_name='prompt voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_voice_it',
            field=models.TextField(blank=True, null=True, verbose_name='prompt voice'),
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_voice_pt',
            field=models.TextField(blank=True, null=True, verbose_name='prompt voice'),
        ),
    ]
