# Generated by Django 5.2.10 on 2026-03-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0025_delete_story_alter_character_exec_on_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic')], null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic')], null=True),
        ),
        migrations.AlterField(
            model_name='prop',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic')], null=True),
        ),
    ]
