# Generated by Django 5.2.10 on 2026-03-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0026_delete_story_alter_action_exec_on_save_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
       
    ]
