# Generated by Django 5.2.10 on 2026-03-24 17:31

import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0027_delete_story'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Video', max_length=200)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_video', to='scene.scene')),
            ],
            bases=(models.Model, task.models.TaskHolder),
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Video', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item', to=settings.FILER_IMAGE_MODEL)),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item_video', to='filer.file')),
            ],
            bases=(models.Model, task.models.TaskHolder),
        ),
    ]
