# Generated by Django 5.2.10 on 2026-03-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0028_scenevideo_videoitem'),
    ]

    operations = [
        
        migrations.AlterModelOptions(
            name='videoitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='videoitem',
            name='scene_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='scene.scenevideo'),
        ),
        migrations.AlterField(
            model_name='scenevideo',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
