# Generated by Django 6.0.3 on 2026-08-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0028_historicalaction_translation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalaction',
            name='audio_voice_en',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='audio_voice_es',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='audio_voice_fr',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='audio_voice_it',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='audio_voice_pt',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='image_comic_en',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='image_comic_es',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='image_comic_fr',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='image_comic_it',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='image_comic_pt',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_comic_en',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_comic_es',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_comic_fr',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_comic_it',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_comic_pt',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_voice_en',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_voice_es',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_voice_fr',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_voice_it',
        ),
        migrations.RemoveField(
            model_name='historicalaction',
            name='prompt_voice_pt',
        ),
    ]
