# Generated by Django 6.0.3 on 2026-08-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0029_remove_historicalaction_audio_voice_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAction',
        ),
    ]
