# Generated by Django 5.2.10 on 2026-03-24 18:35

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0029_delete_story_alter_videoitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenevideo',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_video_video', to='filer.file'),
        ),
    ]
