# Generated by Django 6.0.3 on 2026-08-22 12:20

import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0030_delete_historicalaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='Action', max_length=200, verbose_name='name')),
                ('is_intro', models.SlugField(blank=True, choices=[('scene', 'Scene Intro'), ('story', 'Story Intro')], null=True, verbose_name='is intro')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='prompt')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('prompt_refine', models.TextField(blank=True, null=True, verbose_name='prompt refine')),
                ('prompt_video', models.TextField(blank=True, null=True, verbose_name='prompt video')),
                ('action', models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('generate_scene_voices', 'Generate Voices'), ('generate_scene_comics', 'Generate Comics'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')], null=True, verbose_name='action')),
                ('prompt_comic', models.TextField(blank=True, null=True, verbose_name='prompt comic')),
                ('prompt_voice', models.TextField(blank=True, null=True, verbose_name='prompt voice')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='configuration')),
                ('shot_type', models.CharField(blank=True, choices=[('silent', 'Silent'), ('voice', 'Voice'), ('video', 'Video'), ('comic', 'Comic'), ('video_loop', 'Video Loop')], max_length=20, null=True, verbose_name='shot type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.character', verbose_name='actor')),
                ('audio_voice', filer.fields.file.FilerFileField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.file', verbose_name='audio voice')),
                ('background', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.background', verbose_name='background')),
                ('consistent_with', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.action', verbose_name='consistent with')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('image', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('image_comic', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image comic')),
                ('image_first', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image first')),
                ('image_last', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image last')),
                ('image_refine', filer.fields.image.FilerImageField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='image refine')),
                ('scene', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.scene', verbose_name='scene')),
                ('video', filer.fields.file.FilerFileField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='filer.file', verbose_name='video')),
                ('voice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scene.voice', verbose_name='voice')),
            ],
            options={
                'verbose_name': 'historical Shot',
                'verbose_name_plural': 'historical Shots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
