# Generated by Django 5.2.10 on 2026-03-27 00:34

import agent.models
import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0030_scenevideo_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video')], null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video')], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video')], null=True),
        ),
        migrations.AlterField(
            model_name='prop',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video')], null=True),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Story', max_length=200)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('prompt_refine', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('actors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='scene.character')),
                ('props', models.ManyToManyField(blank=True, related_name='stories', to='scene.prop')),
                ('scenes', models.ManyToManyField(blank=True, related_name='stories', to='scene.scene')),
            ],
            bases=(models.Model, agent.models.GetContentsMixin, task.models.TaskHolder),
        ),
        migrations.CreateModel(
            name='StoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_users', to='scene.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_users', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, agent.models.GetContentsMixin, task.models.TaskHolder),
        ),
    ]
