# Generated by Django 5.2.10 on 2026-03-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0031_alter_action_exec_on_save_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='actors',
        ),
        migrations.AddField(
            model_name='story',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='stories', to='scene.character'),
        ),
    ]
