# Generated by Django 6.0.3 on 2026-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0031_historicalaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Shot', 'verbose_name_plural': 'Shots'},
        ),
        migrations.AddField(
            model_name='historicalstory',
            name='prompt_translations',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Translations'),
        ),
        migrations.AddField(
            model_name='story',
            name='prompt_translations',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt Translations'),
        ),
    ]
