# Generated by Django 5.2.10 on 2026-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0032_remove_story_actors_story_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='backgrounds',
            field=models.ManyToManyField(blank=True, related_name='stories', to='scene.background'),
        ),
        migrations.AlterField(
            model_name='story',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='stories', to='scene.character'),
        ),
    ]
