# Generated by Django on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0033_historicalscene_prompt_translations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='render',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Render Composition', 'verbose_name_plural': 'Render Compositions'},
        ),
        migrations.AddField(
            model_name='render',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='render',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('fr', 'French')], default='en', help_text='The language for voiceovers and localized assets.', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='render',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modified at'),
        ),
    ]
