# Generated by Django 6.0.3 on 2026-04-03 13:22

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0033_story_backgrounds_alter_story_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='image',
        ),
        migrations.RemoveField(
            model_name='character',
            name='expression',
        ),
        migrations.DeleteModel(
            name='RefineAction',
        ),
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='prop',
            options={'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
        migrations.AddField(
            model_name='action',
            name='audio',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audio', to='filer.file'),
        ),
        migrations.DeleteModel(
            name='Expression',
        ),
    ]
