# Generated by Django 6.0.3 on 2026-04-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0034_remove_expression_image_remove_character_expression_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenevideo',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterModelOptions(
            name='videoitem',
            options={'verbose_name': 'Video Shot', 'verbose_name_plural': 'Video Shots'},
        ),
        migrations.AlterField(
            model_name='action',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='scene',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
