# Generated by Django 6.0.3 on 2026-04-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0035_alter_scenevideo_options_alter_videoitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='style',
        ),
        migrations.RemoveField(
            model_name='character',
            name='style',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='image_refine',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='style',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='style',
        ),
        migrations.RemoveField(
            model_name='story',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='story',
            name='backgrounds',
        ),
        migrations.RemoveField(
            model_name='story',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='story',
            name='prompt_refine',
        ),
        migrations.RemoveField(
            model_name='story',
            name='props',
        ),
        migrations.RemoveField(
            model_name='story',
            name='scenes',
        ),
        migrations.AddField(
            model_name='background',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='scene.story'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='scene.story'),
        ),
        migrations.AddField(
            model_name='prop',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='scene.story'),
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='scene.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='scene.style'),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
