# Generated by Django 6.0.3 on 2026-04-09 21:22

import agent.models
import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0036_remove_background_style_remove_character_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='audio',
            new_name='voice',
        ),
        migrations.AddField(
            model_name='action',
            name='prompt_voice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_users', to='scene.scene')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_users', to='scene.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_users', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, agent.models.GetContentsMixin, task.models.TaskHolder),
        ),
        migrations.DeleteModel(
            name='StoryUser',
        ),
    ]
