# Generated by Django 6.0.3 on 2026-04-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0038_userprofile_enable_filters_alter_userprofile_scene_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='encrypted_api_key',
            new_name='api_key',
        ),
    ]
