# Generated by Django 6.0.3 on 2026-04-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0040_rename_apikey_googleapikey_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='api_key',
            new_name='google_api_key',
        ),
    ]
