# Generated by Django 6.0.3 on 2026-04-10 09:32

import agent.models
import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0041_rename_api_key_userprofile_google_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='google_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='story',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='VoiceAction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.AlterField(
            model_name='action',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice')], null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice')], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice')], null=True),
        ),
        migrations.AlterField(
            model_name='prop',
            name='exec_on_save',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice')], null=True),
        ),
        migrations.CreateModel(
            name='StoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_filters', models.BooleanField(default=False)),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_profiles', to='scene.scene')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_profiles', to='scene.story')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, agent.models.GetContentsMixin, task.models.TaskHolder),
        ),
        migrations.DeleteModel(
            name='GoogleApiKey',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
