# Generated by Django 6.0.3 on 2026-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0046_rename_exec_on_save_action_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyprofile',
            name='enable_filters',
            field=models.BooleanField(default=True),
        ),
    ]
