# Generated by Django 6.0.3 on 2026-05-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0051_alter_action_action_alter_background_action_and_more'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='action',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='actions_characters', to='scene.character'),
        ),
    ]
