# Generated by Django 6.0.3 on 2026-05-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0052_remove_action_extras_action_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='characters',
        ),
        migrations.AddField(
            model_name='action',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='actions_cast', to='scene.character'),
        ),
    ]
