# Generated by Django 6.0.3 on 2026-05-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0053_remove_action_characters_action_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
