# Generated by Django 6.0.3 on 2026-05-22 21:19

import django.db.models.deletion
import filer.fields.file
import filer.fields.image
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0054_action_text'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='scene_video',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AddField(
            model_name='story',
            name='render_type',
            field=models.CharField(choices=[('film', 'Film'), ('graphic_novel', 'Graphic Novel'), ('animatic', 'Animatic')], default='animatic', help_text='The default render format for this story.', max_length=50),
        ),
        migrations.AddField(
            model_name='style',
            name='global_default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('render_type', models.CharField(choices=[('film', 'Film'), ('graphic_novel', 'Graphic Novel'), ('animatic', 'Animatic')], default='film', help_text='The format in which this scene will be synthesized.', max_length=50)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='scene.scene')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='scene.story')),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_videos', to='filer.file')),
            ],
            options={
                'verbose_name': 'Render Composition',
                'verbose_name_plural': 'Render Compositions',
            },
            bases=(models.Model, task.models.TaskHolder),
        ),
        migrations.CreateModel(
            name='RenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_items', to='scene.action')),
                ('audio', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item_audio', to='filer.file')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item', to=settings.FILER_IMAGE_MODEL)),
                ('render', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='render_items', to='scene.render')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='render_items', to='scene.scene')),
                ('video', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_item_video', to='filer.file')),
            ],
            options={
                'verbose_name': 'Render Item',
                'verbose_name_plural': 'Render Items',
                'ordering': ['order'],
            },
            bases=(models.Model, task.models.TaskHolder),
        ),
        migrations.DeleteModel(
            name='SceneVideo',
        ),
        migrations.DeleteModel(
            name='VideoItem',
        ),
    ]
