# Generated by Django 6.0.3 on 2026-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0056_contactrequest_theme_remove_scene_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='prompt',
            field=models.TextField(blank=True, default='#Location\n#Cast\n#Props\n#Actions\n', null=True),
        ),
    ]
