# Generated by Django 6.0.3 on 2026-05-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0057_alter_scene_name_alter_scene_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions')], null=True),
        ),
    ]
