# Generated by Django 6.0.3 on 2026-05-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0058_scene_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions')], null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='prompt',
            field=models.TextField(blank=True, default='#Plot\n', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='prompt_refine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
