# Generated by Django 6.0.3 on 2026-05-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0059_story_action_story_prompt_story_prompt_refine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionOrganizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.action',),
        ),
        migrations.AddField(
            model_name='action',
            name='is_intro',
            field=models.SlugField(blank=True, choices=[('scene', 'Scene Intro'), ('story', 'Story Intro')], null=True),
        ),
    ]
