# Generated by Django 6.0.3 on 2026-05-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0060_actionorganizer_action_is_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='contribuition',
            field=models.TextField(blank=True, choices=[('pay', 'I am ok to pay 20/30 dollars/euros'), ('api_key', 'I am ok to bring my google api key to the project'), ('collaborate', 'I want to collaborate in another way'), ('trial', 'I just want to try it out and use the local open source version')], null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='prompt',
            field=models.TextField(blank=True, default='#Location\n#Cast\n#Props\n#Actions\n', help_text='Just imagine and write with as many typos as you want. Guillermo will curate your scene', null=True, verbose_name='A glimpse of your imagination'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='scene.workshop'),
        ),
    ]
