# Generated by Django 6.0.3 on 2026-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0061_workshop_contactrequest_contribuition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='group_number',
            field=models.IntegerField(blank=True, help_text='How many friends and family member you would bring to the workshop?', null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='contribuition',
            field=models.TextField(blank=True, choices=[('pay', 'I am ok to pay 20/30 dollars/euros for the workshop'), ('api_key', 'I am ok to bring my google api key to the project'), ('collaborate', 'I want to collaborate in another way'), ('trial', 'I just want to try it out and use the local open source version')], null=True),
        ),
    ]
