# Generated by Django 6.0.3 on 2026-05-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0062_contactrequest_group_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneOrganizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('scene.scene',),
        ),
    ]
