# Generated by Django 6.0.3 on 2026-05-29 22:14

import agent.models
import django.db.models.deletion
import filer.fields.file
import task.mixins
import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('scene', '0063_sceneorganizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('prompt', models.TextField(blank=True, default='Style: [describe the style of speaking you want, e.g. excited, sad, professional, etc.]\nPace: [describe the pace of speaking you want, e.g. fast, slow, etc.]\nAccent: [describe the accent you want, e.g. British, American, etc.]\n\n', null=True)),
                ('sample_text', models.TextField(blank=True, default='Hello, this is a sample voice. 1, 2, 3. Change me and add a sample prompt for better results. Add audio effects for more interesting voices!', null=True)),
                ('action', models.SlugField(blank=True, choices=[('generate_voice', 'Generate Voice')], null=True)),
                ('audio_voice', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='filer.file')),
            ],
            bases=(task.mixins.AfterSaveActionMixin, models.Model, task.models.TaskHolder, agent.models.GetContentsMixin),
        ),
        migrations.AlterField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='scene.voice'),
        ),
    ]
