# Generated by Django 6.0.3 on 2026-05-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0029_delete_voice'),
        ('scene', '0064_voice_alter_character_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors_stories', to='agent.agent'),
        ),
    ]
