# Generated by Django 6.0.3 on 2026-05-31 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0065_story_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='global_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voice',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='scene.story'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True),
        ),
        migrations.AlterField(
            model_name='prop',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Scene Elements'), ('generate_scene_actions', 'Generate Scene Actions'), ('extract_scene', 'Extract Scene')], null=True),
        ),
    ]
