# Generated by Django 6.0.3 on 2026-05-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0031_googlevoice'),
        ('scene', '0066_voice_global_default_voice_story_alter_action_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='google_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voices', to='agent.googlevoice'),
        ),
    ]
