# Generated by Django 6.0.3 on 2026-05-31 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0067_voice_google_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_voice', to='scene.voice'),
        ),
        migrations.AlterField(
            model_name='render',
            name='render_type',
            field=models.CharField(choices=[('film', 'Film'), ('comic', 'Graphic Novel'), ('animatic', 'Animatic')], default='film', help_text='The format in which this scene will be synthesized.', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='render_type',
            field=models.CharField(choices=[('film', 'Film'), ('comic', 'Graphic Novel'), ('animatic', 'Animatic')], default='animatic', help_text='The default render format for this story.', max_length=50),
        ),
    ]
