# Generated by Django 6.0.3 on 2026-06-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0068_action_voice_alter_render_render_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='code',
        ),
    ]
