# Generated by Django 6.0.3 on 2026-06-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene', '0051_remove_action_extras_action_cast_action_text_and_more'),
        ('scene', '0069_remove_voice_code'),
    ]

    operations = [
    ]
