# Generated by Django 6.0.3 on 2026-08-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Nautilus AccountId string.', max_length=100, unique=True)),
                ('account_type', models.CharField(blank=True, help_text='e.g. CASH, MARGIN, BETTING.', max_length=50)),
                ('base_currency', models.CharField(blank=True, help_text='Base currency code (e.g. USD, EUR).', max_length=10)),
                ('balance_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('balance_free', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('balance_locked', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('balances', models.JSONField(blank=True, default=dict, help_text='Multi-currency balance breakdowns.')),
                ('margins', models.JSONField(blank=True, default=dict, help_text='Margin usage details.')),
                ('info', models.JSONField(blank=True, default=dict, help_text='Additional broker metadata.')),
                ('is_reported', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['account_id'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='If active, this portfolio will be run by the trading node.')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('instrument_id', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('avg_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scanner_class_path', models.CharField(help_text="Full Python path to the scanner class (e.g., 'argo.scanners.volatility.VolatilityScanner').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_params', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the strategy.', max_length=100, unique=True)),
                ('class_path', models.CharField(choices=[('argo.strategies.ema_cross.EMACrossStrategy', 'EMA Crossover Strategy'), ('argo.strategies.mean_reversion.BBMeanReversionStrategy', 'Bollinger Bands Mean Reversion'), ('argo.strategies.rsi.RSIStrategy', 'RSI Mean Reversion'), ('argo.strategies.macd.MACDStrategy', 'MACD Momentum Strategy'), ('argo.strategies.donchian_breakout.DonchianBreakoutStrategy', 'Donchian Breakout (Turtle)'), ('argo.strategies.buy_and_hold.BuyAndHoldStrategy', 'Buy and Hold Benchmark')], help_text="Full Python path to the strategy class (e.g., 'argo.nautilus.strategies.EMACross').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('venue', models.CharField(db_index=True, max_length=32)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURE', 'Future'), ('OPTION', 'Option'), ('FX', 'Forex'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Crypto'), ('INDEX', 'Index')], default='EQUITY', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('quote_currency', models.CharField(blank=True, max_length=8, null=True)),
                ('price_precision', models.PositiveSmallIntegerField(default=2)),
                ('size_precision', models.PositiveSmallIntegerField(default=0)),
                ('price_increment', models.DecimalField(decimal_places=6, default=0.01, max_digits=12)),
                ('size_increment', models.DecimalField(decimal_places=6, default=1.0, max_digits=12)),
                ('lot_size', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', 'venue'],
                'unique_together': {('symbol', 'venue', 'asset_class')},
            },
        ),
        migrations.CreateModel(
            name='IBContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('sec_type', models.CharField(default='STK', help_text='STK, FUT, OPT, CASH, IND, CRYPTO, CFD', max_length=16)),
                ('exchange', models.CharField(default='SMART', max_length=32)),
                ('primary_exchange', models.CharField(blank=True, max_length=32)),
                ('local_symbol', models.CharField(blank=True, max_length=64)),
                ('trading_class', models.CharField(blank=True, max_length=32)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('option_right', models.CharField(blank=True, choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('include_expired', models.BooleanField(default=False)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ib_contract', to='argo.instrument')),
            ],
            options={
                'verbose_name': 'IB Contract',
                'verbose_name_plural': 'IB Contracts',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=100)),
                ('signal_type', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('VIEWED', 'Viewed'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=10)),
                ('confidence', models.FloatField(blank=True, help_text='Confidence score from 0.0 to 1.0.', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Scanner-specific data, e.g., indicator values.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='argo.scanner')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_params', models.JSONField(default=dict, help_text='Suggested parameters for the strategy instance (e.g., stop loss, take profit).')),
                ('justification', models.TextField(blank=True, help_text='Why this strategy is recommended for this signal.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='argo.signal')),
                ('recommended_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='argo.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(help_text="The instrument ID this strategy instance will trade (e.g., 'EUR/USD.CASH.IDEALPRO').", max_length=100)),
                ('params', models.JSONField(blank=True, default=dict, help_text='JSON object of strategy-specific parameters.')),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_instances', to='argo.portfolio')),
                ('strategy_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='argo.strategy')),
            ],
        ),
    ]
