# Generated by Django 6.0.3 on 2026-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short identifier for the group (e.g., 'US_TECH', 'FX_MAJORS').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURE', 'Future'), ('OPTION', 'Option'), ('FX', 'Forex'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Crypto'), ('INDEX', 'Index')], default='EQUITY', max_length=16)),
                ('venue', models.CharField(default='SMART', help_text='Default venue/exchange for instruments in this group.', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('symbols', models.TextField(blank=True, help_text="Comma, space, or newline-separated symbols to populate (e.g., 'AAPL, MSFT, NVDA').")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument Group',
                'verbose_name_plural': 'Instrument Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='instruments', to='argo.instrumentgroup'),
        ),
    ]
