# Generated by Django 6.0.3 on 2026-08-25 13:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_alter_agent_schema'),
        ('argo', '0002_instrumentgroup_instrument_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_symbols-schema-symbols', 'Create symbols from description'), ('generate_text-preset-sync_symbols-schema-symbols', 'Sync symbols'), ('generate_text-preset-symbols_to_json-schema-symbols', 'Turn symbols into JSON'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AddField(
            model_name='instrumentgroup',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors_instrument_groups', to='agent.agent', verbose_name='mentor'),
        ),
        migrations.CreateModel(
            name='HistoricalInstrumentGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, help_text="Short identifier for the group (e.g., 'US_TECH', 'FX_MAJORS').", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURE', 'Future'), ('OPTION', 'Option'), ('FX', 'Forex'), ('COMMODITY', 'Commodity'), ('CRYPTO', 'Crypto'), ('INDEX', 'Index')], default='EQUITY', max_length=16)),
                ('venue', models.CharField(default='SMART', help_text='Default venue/exchange for instruments in this group.', max_length=32)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('symbols', models.TextField(blank=True, help_text="Comma, space, or newline-separated symbols to populate (e.g., 'AAPL, MSFT, NVDA').")),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.SlugField(blank=True, choices=[('generate_text-preset-create_symbols-schema-symbols', 'Create symbols from description'), ('generate_text-preset-sync_symbols-schema-symbols', 'Sync symbols'), ('generate_text-preset-symbols_to_json-schema-symbols', 'Turn symbols into JSON'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.agent', verbose_name='mentor')),
            ],
            options={
                'verbose_name': 'historical Instrument Group',
                'verbose_name_plural': 'historical Instrument Groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
