# Generated by Django 6.0.3 on 2026-08-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0003_instrumentgroup_action_instrumentgroup_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_symbols-target-symbols-schema-outwithmsg', 'Create symbols from description'), ('generate_text-preset-sync_symbols-target-symbols-schema-outwithmsg', 'Sync symbols'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='instrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_symbols-target-symbols-schema-outwithmsg', 'Create symbols from description'), ('generate_text-preset-sync_symbols-target-symbols-schema-outwithmsg', 'Sync symbols'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
