# Generated by Django 6.0.3 on 2026-08-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0004_alter_historicalinstrumentgroup_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstrumentgroup',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='instrumentgroup',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='strategyinstance',
            name='instrument_id',
        ),
        migrations.AddField(
            model_name='strategyinstance',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='The instrument this strategy instance trades.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_instances', to='argo.instrument'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_symbols-target-symbols-schema-outwithmsg', 'Create symbols from description'), ('generate_text-preset-sync_symbols-target-symbols-schema-symbols', 'Sync symbols'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='instrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_symbols-target-symbols-schema-outwithmsg', 'Create symbols from description'), ('generate_text-preset-sync_symbols-target-symbols-schema-symbols', 'Sync symbols'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
