# Generated by Django 6.0.3 on 2026-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0006_alter_portfolio_options_portfolio_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='instrument_groups',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='argo.instrumentgroup'),
        ),
    ]
