# Generated by Django 6.0.3 on 2026-08-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0007_portfolio_instrument_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalportfolio',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_instances-target-description-schema-instances', 'Create instances from description'), ('generate_text-preset-sync_instances-target-description-schema-instances', 'Sync instances'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-create_instances-target-description-schema-instances', 'Create instances from description'), ('generate_text-preset-sync_instances-target-description-schema-instances', 'Sync instances'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
