# Generated by Django 6.0.3 on 2026-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0008_alter_historicalportfolio_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyinstance',
            name='description',
            field=models.TextField(blank=True, help_text='Description or trading rationale for this instance.'),
        ),
    ]
