# Generated by Django 6.0.3 on 2026-09-01 11:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0009_strategyinstance_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyinstance',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-strategy_instance_optimize-schema-optimize', 'Optimize Parameters & Instrument'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='class_path',
            field=models.CharField(choices=[('argo.strategies.ema_cross.EMACrossStrategy', 'EMA Crossover Strategy'), ('argo.strategies.mean_reversion.BBMeanReversionStrategy', 'Bollinger Bands Mean Reversion'), ('argo.strategies.rsi.RSIStrategy', 'RSI Mean Reversion'), ('argo.strategies.macd.MACDStrategy', 'MACD Momentum Strategy'), ('argo.strategies.donchian_breakout.DonchianBreakoutStrategy', 'Donchian Breakout (Turtle)'), ('argo.strategies.supertrend_breakout.SuperTrendBreakoutStrategy', 'SuperTrend Volatility Breakout'), ('argo.strategies.kama_trend.KaufmanAdaptiveTrendStrategy', 'Kaufman Adaptive Trend Strategy'), ('argo.strategies.triple_ma_trend.TripleMAContinuationStrategy', 'Triple EMA Continuation Strategy'), ('argo.strategies.buy_and_hold.BuyAndHoldStrategy', 'Buy and Hold Benchmark')], help_text="Full Python path to the strategy class (e.g., 'argo.nautilus.strategies.EMACross').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='strategyinstance',
            name='strategy_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='argo.strategy'),
        ),
        migrations.CreateModel(
            name='HistoricalStrategyInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description or trading rationale for this instance.')),
                ('params', models.JSONField(blank=True, default=dict, help_text='JSON object of strategy-specific parameters.')),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.SlugField(blank=True, choices=[('generate_text-preset-strategy_instance_optimize-schema-optimize', 'Optimize Parameters & Instrument'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(blank=True, db_constraint=False, help_text='The instrument this strategy instance trades.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argo.instrument')),
                ('portfolio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argo.portfolio')),
                ('strategy_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argo.strategy')),
            ],
            options={
                'verbose_name': 'historical strategy instance',
                'verbose_name_plural': 'historical strategy instances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
