# Generated by Django 6.0.3 on 2026-09-01 13:05

import agent.models
import django.db.models.deletion
import simple_history.models
import task.mixins
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0010_strategyinstance_action_alter_strategy_class_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstrategyinstance',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-optimize-schema-optimize', 'Optimize Parameters & Instrument'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='strategyinstance',
            name='action',
            field=models.SlugField(blank=True, choices=[('generate_text-preset-optimize-schema-optimize', 'Optimize Parameters & Instrument'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Experiment name (e.g. '2024 Macro Trend Run').", max_length=150)),
                ('start_date', models.DateTimeField(help_text='Backtest start timestamp.')),
                ('end_date', models.DateTimeField(help_text='Backtest end timestamp.')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000.0, max_digits=18)),
                ('commission_rate', models.FloatField(default=0.0001, help_text='Simulated broker commission percentage.')),
                ('params_override', models.JSONField(blank=True, default=dict, help_text='Specific parameters override for single backtest.')),
                ('param_grid', models.JSONField(blank=True, default=dict, help_text='Parameter ranges for optimization sweep.')),
                ('optimization_objective', models.CharField(choices=[('sharpe', 'Sharpe Ratio'), ('calmar', 'Calmar Ratio'), ('profit_factor', 'Profit Factor'), ('pnl', 'Total PnL')], default='sharpe', max_length=50)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('sortino_ratio', models.FloatField(blank=True, null=True)),
                ('calmar_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown_pct', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('best_params', models.JSONField(blank=True, default=dict, help_text='Optimal parameters from sweep.')),
                ('leaderboard', models.JSONField(blank=True, default=list, help_text='Ranked leaderboard of parameter combinations.')),
                ('action', models.SlugField(blank=True, choices=[('run_backtest', 'Run Backtest'), ('run_optimization', 'Run Parameter Optimization'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_instance', models.ForeignKey(help_text='The StrategyInstance being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='argo.strategyinstance')),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
                'ordering': ['-created_at'],
            },
            bases=(task.mixins.AfterSaveActionMixin, models.Model, agent.models.GetContentsMixin, task.models.TaskHolder),
        ),
        migrations.CreateModel(
            name='HistoricalBacktest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Experiment name (e.g. '2024 Macro Trend Run').", max_length=150)),
                ('start_date', models.DateTimeField(help_text='Backtest start timestamp.')),
                ('end_date', models.DateTimeField(help_text='Backtest end timestamp.')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000.0, max_digits=18)),
                ('commission_rate', models.FloatField(default=0.0001, help_text='Simulated broker commission percentage.')),
                ('params_override', models.JSONField(blank=True, default=dict, help_text='Specific parameters override for single backtest.')),
                ('param_grid', models.JSONField(blank=True, default=dict, help_text='Parameter ranges for optimization sweep.')),
                ('optimization_objective', models.CharField(choices=[('sharpe', 'Sharpe Ratio'), ('calmar', 'Calmar Ratio'), ('profit_factor', 'Profit Factor'), ('pnl', 'Total PnL')], default='sharpe', max_length=50)),
                ('total_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('return_pct', models.FloatField(blank=True, null=True)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('sortino_ratio', models.FloatField(blank=True, null=True)),
                ('calmar_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown_pct', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('best_params', models.JSONField(blank=True, default=dict, help_text='Optimal parameters from sweep.')),
                ('leaderboard', models.JSONField(blank=True, default=list, help_text='Ranked leaderboard of parameter combinations.')),
                ('action', models.SlugField(blank=True, choices=[('run_backtest', 'Run Backtest'), ('run_optimization', 'Run Parameter Optimization'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('strategy_instance', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argo.strategyinstance')),
            ],
            options={
                'verbose_name': 'historical Backtest',
                'verbose_name_plural': 'historical Backtests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
