# Generated by Django 6.0.3 on 2026-09-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0011_alter_historicalstrategyinstance_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbacktest',
            name='strategy_instance',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The StrategyInstance being evaluated.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='argo.strategyinstance'),
        ),
    ]
