# Generated by Django 6.0.3 on 2026-09-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0012_alter_historicalbacktest_strategy_instance'),
    ]

    operations = [

    ]
