# Generated by Django 6.0.3 on 2026-09-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0013_alter_backtest_strategy_instance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBacktest',
        ),
    ]
