# Generated by Django 6.0.3 on 2026-09-01 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0014_delete_historicalbacktest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='strategy_instance',
            field=models.ForeignKey(help_text='The StrategyInstance being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='argo.strategyinstance'),
        ),
    ]
