# Generated by Django 6.0.3 on 2026-09-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0015_alter_backtest_strategy_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_type', models.CharField(help_text="Nautilus BarType identifier (e.g. 'EURUSD.IDEALPRO-1-MINUTE-MID-INTERNAL').", max_length=120)),
                ('start_date', models.DateTimeField(help_text='Start timestamp of the dataset.')),
                ('end_date', models.DateTimeField(help_text='End timestamp of the dataset.')),
                ('bar_count', models.PositiveIntegerField(default=0, help_text='Total number of bars in this dataset.')),
                ('source', models.CharField(choices=[('ib_gateway', 'Interactive Brokers Gateway'), ('catalog', 'Parquet Data Catalog'), ('synthetic', 'Synthetic Simulation')], default='catalog', help_text='Origin source of the historical data.', max_length=30)),
                ('catalog_path', models.CharField(default='./catalog', help_text='Filesystem directory path of the ParquetDataCatalog.', max_length=255)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Key summary statistics (open, high, low, close, volume).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(help_text='The instrument this data series belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_datasets', to='argo.instrument')),
            ],
            options={
                'verbose_name': 'Historical Data',
                'verbose_name_plural': 'Historical Data',
                'ordering': ['-end_date'],
                'indexes': [models.Index(fields=['instrument', 'bar_type', 'start_date', 'end_date'], name='argo_histor_instrum_f1b13a_idx')],
            },
        ),
        migrations.AddField(
            model_name='backtest',
            name='historical_data',
            field=models.ForeignKey(blank=True, help_text='Persisted historical market data used for this backtest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='argo.historicaldata'),
        ),
    ]
