# Generated by Django 6.0.3 on 2026-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0016_historicaldata_backtest_historical_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historicaldata',
            new_name='argo_histor_instrum_427efe_idx',
            old_name='argo_histor_instrum_f1b13a_idx',
        ),
        migrations.AlterField(
            model_name='backtest',
            name='action',
            field=models.SlugField(blank=True, choices=[('load_data', 'Load Historical Data'), ('run_backtest', 'Run Backtest'), ('run_optimization', 'Run Parameter Optimization'), ('generate_text-preset-info', 'Info'), ('generate_text-preset-instruction-schema-outwithmsg', 'Instruction'), ('generate_text-preset-instruction-schema-create_instructions', 'Instruction Commit')], max_length=1024, null=True, verbose_name='action'),
        ),
    ]
