# Generated by Django on 2026-09-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0017_rename_argo_histor_instrum_f1b13a_idx_argo_histor_instrum_427efe_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstrategyinstance',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='strategyinstance',
            name='portfolio',
        ),
    ]
