# Generated by Django 6.0.3 on 2026-09-09

from django.db import migrations, models


def convert_symbols_to_json(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            UPDATE argo_instrumentgroup
            SET symbols = CASE
                WHEN symbols IS NULL OR trim(symbols) = '' THEN '[]'
                WHEN symbols ~ '^\\s*\\[.*\\]\\s*$' THEN symbols
                ELSE to_json(regexp_split_to_array(trim(symbols), '[\\s,;]+'))::text
            END;
        """)
        schema_editor.execute("""
            UPDATE argo_historicalinstrumentgroup
            SET symbols = CASE
                WHEN symbols IS NULL OR trim(symbols) = '' THEN '[]'
                WHEN symbols ~ '^\\s*\\[.*\\]\\s*$' THEN symbols
                ELSE to_json(regexp_split_to_array(trim(symbols), '[\\s,;]+'))::text
            END;
        """)
    else:
        import json
        import re
        db_alias = schema_editor.connection.alias
        InstrumentGroup = apps.get_model('argo', 'InstrumentGroup')
        HistoricalInstrumentGroup = apps.get_model('argo', 'HistoricalInstrumentGroup')
        for model in (InstrumentGroup, HistoricalInstrumentGroup):
            for obj in model.objects.using(db_alias).all():
                raw = obj.symbols
                if not raw or not str(raw).strip():
                    obj.symbols = '[]'
                else:
                    raw_str = str(raw).strip()
                    if not (raw_str.startswith('[') and raw_str.endswith(']')):
                        tokens = [s.strip().upper() for s in re.split(r'[\s,;]+', raw_str) if s.strip()]
                        obj.symbols = json.dumps(tokens)
                obj.save(update_fields=['symbols'])


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0018_remove_strategyinstance_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstrumentgroup',
            name='asset_class',
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentgroup',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentgroup',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='instrumentgroup',
            name='asset_class',
        ),
        migrations.RemoveField(
            model_name='instrumentgroup',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='instrumentgroup',
            name='venue',
        ),
        migrations.AlterField(
            model_name='historicalinstrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('search_and_create_instruments', 'Search IB & Create Instruments')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='instrumentgroup',
            name='action',
            field=models.SlugField(blank=True, choices=[('search_and_create_instruments', 'Search IB & Create Instruments')], max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.RunPython(
            convert_symbols_to_json,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='historicalinstrumentgroup',
            name='symbols',
            field=models.JSONField(blank=True, default=list, help_text='JSON vector/list of symbols or queries to search and create instruments for.'),
        ),
        migrations.AlterField(
            model_name='instrumentgroup',
            name='symbols',
            field=models.JSONField(blank=True, default=list, help_text='JSON vector/list of symbols or queries to search and create instruments for.'),
        ),
    ]
