# Generated by Django 6.0.3 on 2026-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0019_remove_historicalinstrumentgroup_asset_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='source',
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='bar_type',
            field=models.CharField(choices=[('1-SECOND', '1 Second'), ('1-MINUTE', '1 Minute'), ('5-MINUTE', '5 Minutes'), ('15-MINUTE', '15 Minutes'), ('30-MINUTE', '30 Minutes'), ('1-HOUR', '1 Hour'), ('4-HOUR', '4 Hours'), ('1-DAY', '1 Day'), ('1-WEEK', '1 Week'), ('1-MONTH', '1 Month')], default='1-MINUTE', help_text='Bar aggregation timeframe choice.', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='catalog_path',
            field=models.CharField(blank=True, help_text='Filesystem directory path of the Parquet dataset for this instrument.', max_length=512),
        ),
    ]
