# Generated by Django 6.0.3 on 2026-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0020_remove_historicaldata_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='action',
            field=models.SlugField(
                blank=True,
                choices=[('load_data', 'Load Historical Data')],
                help_text='Trigger a background action task upon save.',
                max_length=1024,
                null=True,
                verbose_name='action',
            ),
        ),
    ]
