# Generated by Django 6.0.3 on 2026-09-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('argo', '0021_historicaldata_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='historical_data',
        ),
    ]
