"""
Django settings for screenplay project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.urls import reverse_lazy
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))
GOOGLE_GENAI_VERTEX_API_KEY= os.getenv("GOOGLE_GENAI_VERTEX_API_KEY")

DEBUG=True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
MEDIA_ROOT = os.path.join( BASE_DIR , 'media' )
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


SITE_URL = os.getenv("SITE_URL")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['178.238.234.86', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['178.238.234.86', 'guillermoai.duckdns.org', 'www.guillermoai.duckdns.org', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',
    'filer',
    'scene.apps.SceneConfig',
    'agent.apps.AgentConfig',
    'task',
    'brainstorm'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


def agentprofile(request):
    try:
        return f"/admin/agent/agentprofile/{request.user.story_profile.id}/change/?next=/admin/scene/story/"
    except:
        return "/admin/"
def token_usage_link(request):
    return "/admin/agent/tokenusage/"

def storyprofile(request):
    try:
        return f"/admin/scene/storyprofile/{request.user.story_profile.id}/change/?next=/admin/scene/story/"
    except:
        return "/admin/scene/storyprofile/"


from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": "Guillermo",  # Appears in the title and in the top left corner
    "SITE_HEADER": "Guillermo",
    "SITE_SUBHEADER": "Tell me a story",
    "STYLES": [
        lambda request: static("css/unfold_filer_custom.css"),
        lambda request: static("css/custom.css"),
    ],
    "DASHBOARD_CALLBACK": "brainstorm.models.dashboard_callback",
    "ACCOUNT": {}, # Empty this to prevent duplication at the bottom
    
    "COLORS": {
      "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-700)",  # text-base-900
            "important-dark": "var(--color-base-300)",  # text-base-100
        },  
    },
    "SIDEBAR": {
        "show_all_applications": True,
        "show_user": True,                 # Ensure user profile is visible at the bottom
        "navigation": [
            {
                "title": "Co-Writing Scripts",
                "items": [
                    {
                        "title": "Themes",
                        "icon": "palette",
                        "link": reverse_lazy("admin:brainstorm_theme_changelist"),
                    },
                    {
                        "title": "Scripts",
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:brainstorm_session_changelist"),
                    },
                    {
                        "title": "Creative Groups",
                        "icon": "groups",
                        "link": reverse_lazy("admin:scene_storygroup_changelist"),
                    }

                ],
            },
            {
                "title": "Storytelling",
                "separator": True,
                "items": [
                    {
                        "title": "Stories",
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:scene_story_changelist"),
                    },
                    {
                        "title": "Elements",
                        "icon": "category",
                        "link": reverse_lazy("admin:scene_prop_changelist"),
                    },
                    {
                        "title": "Characters",
                        "icon": "person",
                        "link": reverse_lazy("admin:scene_character_changelist"),
                    },
                    {
                        "title": "Locations",
                        "icon": "location_on",
                        "link": reverse_lazy("admin:scene_background_changelist"),
                    },
                    {
                        "title": "Scenes",
                        "icon": "movie",
                        "link": reverse_lazy("admin:scene_scene_changelist"),
                    },

                    {
                        "title": "Actions",
                        "icon": "play_arrow",
                        "link": reverse_lazy("admin:scene_action_changelist"),
                    },
                    {
                        "title": "Comic Actions",
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:scene_comicaction_changelist"),
                    },
                    {
                        "title": "Video Actions",
                        "icon": "videocam",
                        "link": reverse_lazy("admin:scene_videoaction_changelist"),
                    },
                    {
                        "title": "Voice Actions",
                        "icon": "mic",
                        "link": reverse_lazy("admin:scene_voiceaction_changelist"),
                    },
                ],
            },
             {
                "title": "Personal Area",
                "separator": True,
                "items": [
                    {
                        "title": "Story Filters",
                        "icon": "settings",
                        "link": storyprofile,
                    },
                    {
                        "title": "My Apis",
                        "icon": "api",
                        "link": agentprofile,
                    },
                    {
                        "title": "Token Usage",
                        "icon": "monitoring",
                        "link": token_usage_link,
                    }
                ],
            },
            {
                "title": "Distribution",
                "separator": True,
                "items": [
                    {
                        "title": "Videos",
                        "icon": "video_library",
                        "link": reverse_lazy("admin:scene_scenevideo_changelist"),
                    },
                    {
                        "title": "Video Shots",
                        "icon": "grid_view",
                        "link": reverse_lazy("admin:scene_videoitem_changelist"),
                    },
                ],
            },
        ],
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME", "guillermo"),
        'USER': os.getenv("DB_USER", "myuser"),
        'PASSWORD': os.getenv("DB_PASSWORD", "mypassword"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


GOOGLE_GENAI_VERTEX_API_KEY= os.getenv("GOOGLE_GENAI_VERTEX_API_KEY")
FILER_TABLE_ICON_SIZE = 200

USE_TASK_QUEUE = True

CELERY_BROKER_URL = "sqla+sqlite:///celerydb.sqlite"
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


TASK_TYPE_GENERATE_IMAGE = 'generate_image'
TASK_TYPE_REFINE_IMAGE = 'refine_image'
TASK_TYPE_GENERATE_VIDEO = 'generate_video'
TASK_TYPE_GENERATE_VIDEO_FIRST_LAST = 'generate_video_first_last'
TASK_TYPE_GENERATE_COMIC = 'generate_comic'
TASK_TYPE_GENERATE_SCENE_VIDEO = 'generate_scene_video'
TASK_TYPE_GENERATE_VOICE = 'generate_voice'
TASK_TYPE_GENERATE_TEXT = 'generate_text'
TASK_TYPE_GENERATE_SCENE = 'generate_scene'




TASK_DELEGATES = {
    TASK_TYPE_GENERATE_IMAGE: 'scene.tasks.TaskGenerateImage',
    TASK_TYPE_REFINE_IMAGE: 'scene.tasks.TaskRefineImage',
    TASK_TYPE_GENERATE_VIDEO: 'scene.tasks.TaskGenerateVideo',
    TASK_TYPE_GENERATE_VIDEO_FIRST_LAST: 'scene.tasks.TaskGenerateVideoFirstLast',
    TASK_TYPE_GENERATE_COMIC: 'scene.tasks.TaskGenerateComic',
    TASK_TYPE_GENERATE_SCENE_VIDEO: 'scene.tasks.TaskGenerateSceneVideo',
    TASK_TYPE_GENERATE_VOICE: 'scene.tasks.TaskGenerateVoice',
    TASK_TYPE_GENERATE_TEXT: 'scene.tasks.TaskGenerateText',
    TASK_TYPE_GENERATE_SCENE: 'scene.tasks.TaskGenerateScene'
}

TASK_TYPE_CHOICES = (
    (TASK_TYPE_GENERATE_IMAGE, "Generate Image"),
    (TASK_TYPE_REFINE_IMAGE, "Refine Image"),
    (TASK_TYPE_GENERATE_VIDEO, "Generate Video"),
    (TASK_TYPE_GENERATE_VIDEO_FIRST_LAST, "Video First Last"),
    (TASK_TYPE_GENERATE_COMIC, "Generate Comic"),
    (TASK_TYPE_GENERATE_SCENE_VIDEO, "Generate Scene Video"),
    (TASK_TYPE_GENERATE_VOICE, "Generate Voice"),
    (TASK_TYPE_GENERATE_TEXT, "Generate Text"),
    (TASK_TYPE_GENERATE_SCENE, "Generate Scene")
)



# --- Configuración de archivos estáticos ---
import os
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
