"""
Django settings for screenplay project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=os.path.join(BASE_DIR, '.env'))
GOOGLE_GENAI_VERTEX_API_KEY= os.getenv("GOOGLE_GENAI_VERTEX_API_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
MEDIA_ROOT = os.path.join( BASE_DIR , 'media' )
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


SITE_URL = os.getenv("SITE_URL")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['178.238.234.86', 'localhost', '127.0.0.1']
ALLOWED_HOSTS = ['178.238.234.86', 'guillermoai.duckdns.org', 'www.guillermoai.duckdns.org', 'guillermo.studio', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',
    'filer',
    'scene.apps.SceneConfig',
    'agent.apps.AgentConfig',
    'task',
    'import_export',
    'unfold.contrib.import_export'    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# Brevo SMTP Server configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True


# Authentication credentials
# The login username is always the email address linked to your Brevo account
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Your long Brevo SMTP key (looks like xsmtpsib-...)
EMAIL_HOST_PASSWORD = os.environ.get('SMTP_KEY', '')

# Default sender settings
# CRITICAL: This email address MUST be verified in your Brevo Sender dashboard
DEFAULT_FROM_EMAIL = 'Guillermo By Elio <noreply@guillermo.studio>'
SERVER_EMAIL = 'admin@guillermo.studio'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    }
]

WSGI_APPLICATION = 'project.wsgi.application'


def agentprofile(request):
    try:
        return f"/admin/agent/agentprofile/{request.user.story_profile.id}/change/?next=/admin/scene/story/"
    except:
        return "/admin/"
def token_usage_link(request):
    return "/admin/agent/tokenusage/"

def storyprofile(request):
    try:
        return f"/admin/scene/storyprofile/{request.user.story_profile.id}/change/?next=/admin/scene/story/"
    except:
        return "/admin/scene/storyprofile/"


from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": _("Guillermo"),  # Appears in the title and in the top left corner
    "SITE_HEADER": _("Guillermo"),
    "SITE_SUBHEADER": _("The power of your story"),
    "STYLES": [
        lambda request: static("css/unfold_filer_custom.css"),
        lambda request: static("css/custom.css"),
    ],
    "DASHBOARD_CALLBACK": "scene.models.dashboard_callback",
    "ACCOUNT": {}, # Empty this to prevent duplication at the bottom
    
    "COLORS": {
      "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-700)",  # text-base-900
            "important-dark": "var(--color-base-300)",  # text-base-100
        },  
    },
    "SIDEBAR": {
        "show_all_applications": True,
        "show_user": True,                 # Ensure user profile is visible at the bottom
        "navigation": [
            {
                "title": _("Co-Writing"),
                "items": [
                    {
                        "title": _("Stories"),
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:scene_story_changelist"),
                    },
                    {
                        "title": _("Scene Refine & Extract"),
                        "icon": "movie",
                        "link": reverse_lazy("admin:scene_scene_changelist"),
                    },
                    {
                        "title": _("Scene Organizer"),
                        "icon": "movie",
                        "link": reverse_lazy("admin:scene_sceneorganizer_changelist"),
                    },
                ]
            },
            {
                "title": _("Elements"),
                "separator": True,
                "items": [
                    
                    {
                        "title": _("Props"),
                        "icon": "category",
                        "link": reverse_lazy("admin:scene_prop_changelist"),
                    },
                    {
                        "title": _("Characters"),
                        "icon": "person",
                        "link": reverse_lazy("admin:scene_character_changelist"),
                    },
                    {
                        "title": _("Locations"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:scene_background_changelist"),
                    },
                    {
                        "title": _("Voices"),
                        "icon": "record_voice_over",
                        "link": reverse_lazy("admin:scene_voice_changelist"),
                    },
                ]
            },
            {
                "title": _("Actions"),
                "separator": True,
                "items": [

                    {
                        "title": _("Image Actions"),
                        "icon": "play_arrow",
                        "link": reverse_lazy("admin:scene_action_changelist"),
                    },
                    {
                        "title": _("Comic Actions"),
                        "icon": "auto_awesome",
                        "link": reverse_lazy("admin:scene_comicaction_changelist"),
                    },
                    {
                        "title": _("Video Actions"),
                        "icon": "videocam",
                        "link": reverse_lazy("admin:scene_videoaction_changelist"),
                    },
                    {
                        "title": _("Voice Actions"),
                        "icon": "mic",
                        "link": reverse_lazy("admin:scene_voiceaction_changelist"),
                    },
                    {
                        "title": _("Action Organizer"),
                        "icon": "play_arrow",
                        "link": reverse_lazy("admin:scene_actionorganizer_changelist"),
                    },
                ],
            },
            {
                "title": _("Personal Area"),
                "separator": True,
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:scene_storygroup_changelist"),
                    },
                    {
                        "title": _("Story Filters"),
                        "icon": "settings",
                        "link": storyprofile,
                    },
                    {
                        "title": _("My Apis"),
                        "icon": "api",
                        "link": agentprofile,
                    },
                    {
                        "title": _("Token Usage"),
                        "icon": "monitoring",
                        "link": token_usage_link,
                    }
                ],
            },
            {
                "title": _("Rendering"),
                "separator": True,
                "items": [
                    {
                        "title": _("Renders"),
                        "icon": "video_library",
                        "link": reverse_lazy("admin:scene_render_changelist"),
                    },
                    {
                        "title": _("Render Items"),
                        "icon": "grid_view",
                        "link": reverse_lazy("admin:scene_renderitem_changelist"),
                    },
                ],
            },
        ],
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_TYPE = os.getenv("DATABASE_TYPE", "postgresql")

if DATABASE_TYPE == "sqlite":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME", "guillermo"),
            'USER': os.getenv("DB_USER", "postgres"),
            'PASSWORD': os.getenv("DB_PASSWORD", ""),
            'HOST': os.getenv("DB_HOST", "localhost"),
            'PORT': os.getenv("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
]

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


GOOGLE_GENAI_VERTEX_API_KEY= os.getenv("GOOGLE_GENAI_VERTEX_API_KEY")
FILER_TABLE_ICON_SIZE = 200

USE_TASK_QUEUE = True

CELERY_BROKER_TYPE = os.getenv("CELERY_BROKER_TYPE", "sqlite")
if CELERY_BROKER_TYPE == "sqlite":
    CELERY_BROKER_URL = "sqla+sqlite:///celerydb.sqlite"
else:
    CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


TASK_TYPE_GENERATE_IMAGE = 'generate_image'
TASK_TYPE_REFINE_IMAGE = 'refine_image'
TASK_TYPE_GENERATE_VIDEO = 'generate_video'
TASK_TYPE_GENERATE_VIDEO_FIRST_LAST = 'generate_video_first_last'
TASK_TYPE_GENERATE_COMIC = 'generate_comic'
TASK_TYPE_GENERATE_SCENE_VIDEO = 'generate_scene_video'
TASK_TYPE_GENERATE_VOICE = 'generate_voice'
TASK_TYPE_GENERATE_TEXT = 'generate_text'
TASK_TYPE_GENERATE_SCENE = 'generate_scene'
TASK_TYPE_GENERATE_SCENE_ELEMENTS = 'generate_scene_elements'
TASK_TYPE_GENERATE_SCENE_ACTIONS = 'generate_scene_actions'
TASK_TYPE_EXTRACT_SCENE = 'extract_scene'




TASK_DELEGATES = {
    TASK_TYPE_GENERATE_IMAGE: 'scene.tasks.TaskGenerateImage',
    TASK_TYPE_REFINE_IMAGE: 'scene.tasks.TaskRefineImage',
    TASK_TYPE_GENERATE_VIDEO: 'scene.tasks.TaskGenerateVideo',
    TASK_TYPE_GENERATE_VIDEO_FIRST_LAST: 'scene.tasks.TaskGenerateVideoFirstLast',
    TASK_TYPE_GENERATE_COMIC: 'scene.tasks.TaskGenerateComic',
    TASK_TYPE_GENERATE_SCENE_VIDEO: 'scene.tasks.TaskGenerateSceneVideo',
    TASK_TYPE_GENERATE_VOICE: 'scene.tasks.TaskGenerateVoice',
    TASK_TYPE_GENERATE_TEXT: 'scene.tasks.TaskGenerateText',
    TASK_TYPE_GENERATE_SCENE: 'scene.tasks.TaskGenerateScene',
    TASK_TYPE_GENERATE_SCENE_ELEMENTS: 'scene.tasks.TaskGenerateSceneElements',
    TASK_TYPE_GENERATE_SCENE_ACTIONS: 'scene.tasks.TaskGenerateSceneActions',
    TASK_TYPE_EXTRACT_SCENE: 'scene.tasks.TaskExtractScene',
}

TASK_TYPE_CHOICES = (
    (TASK_TYPE_GENERATE_IMAGE, _("Generate Image")),
    (TASK_TYPE_REFINE_IMAGE, _("Refine Image")),
    (TASK_TYPE_GENERATE_VIDEO, _("Generate Video")),
    (TASK_TYPE_GENERATE_VIDEO_FIRST_LAST, _("Video First Last")),
    (TASK_TYPE_GENERATE_COMIC, _("Generate Comic")),
    (TASK_TYPE_GENERATE_SCENE_VIDEO, _("Generate Scene Video")),
    (TASK_TYPE_GENERATE_VOICE, _("Generate Voice")),
    (TASK_TYPE_GENERATE_TEXT, _("Generate Text")),
    (TASK_TYPE_GENERATE_SCENE, _("Generate Scene")),
    (TASK_TYPE_GENERATE_SCENE_ELEMENTS, _("Generate Scene Elements")),
    (TASK_TYPE_GENERATE_SCENE_ACTIONS, _("Generate Scene Actions")),
    (TASK_TYPE_EXTRACT_SCENE, _("Extract Scene"))
)



# --- Configuración de archivos estáticos ---
import os
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Agent Structured Output Schema Settings
SCHEMA_MULTI_SCENE = "multi_scene"
SCHEMA_SCENE = "scene"
AGENT_SCHEMA_CHOICES = [
    (SCHEMA_MULTI_SCENE, _("Multi Scene Storyboard")),
    (SCHEMA_SCENE, _("Single Scene Storyboard")),
]

AGENT_SCHEMAS = {
    SCHEMA_MULTI_SCENE: "scene.schemas.MultiSceneSchema",
    SCHEMA_SCENE : "scene.schemas.SceneSchema",    
}
