# Generated by Django 5.2.9 on 2026-03-12 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField()),
                ('preset_type', models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'YouTube Playlist Create'), ('playlist_item_create', 'YouTube Playlist Item Create')])),
                ('system_default', models.BooleanField(default=False, verbose_name='Default')),
                ('preset', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.PositiveIntegerField()),
                ('obj_id', models.PositiveIntegerField(blank=True, null=True)),
                ('thr_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (0, 'Started'), (4, 'Success'), (3, 'Error'), (2, 'Holding')], default=1)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('task_type', models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'YouTube Playlist Create'), ('playlist_item_create', 'YouTube Playlist Item Create')])),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('obj_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='contenttypes.contenttype')),
                ('thr_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thr', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['status', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('level', models.SlugField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
