# Generated by Django 5.2.9 on 2026-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('answers', 'Refresh Answers'), ('metrics', 'Refresh Metrics')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('answers', 'Refresh Answers'), ('metrics', 'Refresh Metrics')]),
        ),
    ]
