# Generated by Django 5.2.10 on 2026-03-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_task_type_alter_taskpreset_preset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Generate Video First Last')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Generate Video First Last')]),
        ),
    ]
