# Generated by Django 5.2.10 on 2026-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_type_alter_taskpreset_preset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_comic', 'Generate Comic'), ('generate_scene_video', 'Generate Scene Video')]),
        ),
    ]
