# Generated by Django 6.0.3 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_type_alter_taskpreset_preset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='retry_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='retry_countdown',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='task',
            name='retry_max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
