# Generated by Django 6.0.3 on 2026-07-09 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('task', '0005_task_retry_attempts_task_retry_countdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='scheduled at'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_task',
            field=models.OneToOneField(blank=True, help_text='Link to the scheduled task in Django Celery Beat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_task', to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='retry_countdown',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Started'), (4, 'Success'), (3, 'Error'), (2, 'Holding'), (5, 'Scheduled')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('generate_image', 'Generate Image'), ('refine_image', 'Refine Image'), ('generate_video', 'Generate Video'), ('generate_video_first_last', 'Video First Last'), ('generate_video_multimodal', 'Video Multimodal'), ('generate_comic', 'Generate Comic'), ('video_render', 'Render Video'), ('generate_voice', 'Generate Voice'), ('generate_text', 'Generate Text'), ('generate_scene', 'Generate Scene'), ('generate_scene_elements', 'Generate Elements'), ('generate_scene_actions', 'Generate Shots'), ('extract_scene', 'Extract Scene'), ('sync_export', 'Sync Export'), ('sync_import', 'Sync Import'), ('generate_scene', 'Generate Scene Video')]),
        ),
    ]
