# Generated by Django 6.0.3 on 2026-09-01 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('task', '0009_alter_task_task_type_alter_taskpreset_preset_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['subject_ct', 'subject_id'], name='task_task_subject_d932f8_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['obj_ct', 'obj_id'], name='task_task_obj_ct__3c0fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['thr_ct', 'thr_id'], name='task_task_thr_ct__324a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-modified', 'status'], name='task_task_modifie_f9d4a6_idx'),
        ),
    ]
