# Generated by Django 6.0.3 on 2026-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_task_type_alter_taskpreset_preset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('generate_text', 'Generate Text')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('generate_text', 'Generate Text')]),
        ),
    ]
