# Generated by Django 3.1.4 on 2020-12-28 11:35

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1023)),
                ('rate', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='AudioAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AudioGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1023, unique=True)),
                ('description', models.TextField()),
                ('preset', models.JSONField()),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='HyperFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file')),
            ],
        ),
        migrations.CreateModel(
            name='ITask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.PositiveIntegerField()),
                ('obj_id', models.PositiveIntegerField()),
                ('thr_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Error')], default=0)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Analysis'), (1, 'Synthesys'), (2, 'Video')], default=0)),
                ('depend_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.itask')),
                ('obj_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='contenttypes.contenttype')),
                ('subject_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='contenttypes.contenttype')),
                ('thr_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thr', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('variant', models.BooleanField(default=True)),
                ('iso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_human', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1023)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1023)),
                ('extended', models.TextField(blank=True, help_text='Optional. Replace the title for extended texts.', null=True)),
                ('count_char', models.IntegerField(blank=True, null=True)),
                ('count_vowels', models.IntegerField(blank=True, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.language')),
                ('tags', models.ManyToManyField(blank=True, to='is_core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField()),
                ('preset', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=1023)),
                ('api_id', models.CharField(max_length=1023)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.bucket')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1023, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('url', models.URLField(verbose_name='Video Url')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.hyperfile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.text')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField()),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('audio_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.videogenerator')),
                ('video_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.audiogenerator')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.audio')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.tutorial')),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.tutorialgenerator'),
        ),
        migrations.AddField(
            model_name='text',
            name='tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.tutorial'),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.itask')),
            ],
        ),
        migrations.AddField(
            model_name='itask',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.worker'),
        ),
        migrations.CreateModel(
            name='BucketFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=1023)),
                ('order', models.IntegerField(default=0)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.bucket')),
                ('hyper_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.hyperfile')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.audioanalysis'),
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.hyperfile'),
        ),
        migrations.AddField(
            model_name='audio',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.speaker'),
        ),
    ]
