# Generated by Django 3.1.4 on 2020-12-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='is_core.Tag'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='texts',
            field=models.ManyToManyField(through='is_core.TutorialText', to='is_core.Text'),
        ),
    ]
