# Generated by Django 3.1.4 on 2020-12-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('is_core', '0008_auto_20201230_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='thr_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thr', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='thr_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
