# Generated by Django 3.1.5 on 2021-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0015_auto_20210111_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='level',
            field=models.SlugField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error'),
        ),
    ]
