# Generated by Django 3.1.5 on 2021-01-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0018_auto_20210113_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='uploaded',
            new_name='upload',
        ),
    ]
