# Generated by Django 3.1.5 on 2021-01-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0020_video_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='is_core.Language'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Started'), (4, 'Success'), (3, 'Error'), (2, 'Holding')], default=1),
        ),
    ]
