# Generated by Django 3.1.5 on 2021-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0021_auto_20210121_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
