# Generated by Django 3.1.5 on 2021-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0023_auto_20210123_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='external_id',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma separated', max_length=1023, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='privacyStatus',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=1023, verbose_name='PrivacyStatus'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Url'),
        ),
    ]
