# Generated by Django 3.1.5 on 2021-01-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0025_tutorial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='languages',
            field=models.ManyToManyField(blank=True, to='is_core.Language'),
        ),
    ]
