# Generated by Django 3.1.5 on 2021-01-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0026_auto_20210124_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.text'),
        ),
    ]
