# Generated by Django 3.1.5 on 2021-05-10 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0032_tutorial_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple')]),
        ),
    ]
