# Generated by Django 3.1.5 on 2024-10-03 10:06

from django.db import migrations, models
import django.db.models.deletion
import is_core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0036_auto_20221013_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrasformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1024, null=True)),
                ('payload', models.JSONField(null=True)),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='is_core.audio')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='is_core.audio')),
            ],
            bases=(models.Model, is_core.utils.ModelDiffMixin),
        ),
    ]
