# Generated by Django 6.0.3 on 2026-06-01 04:43

import django.db.models.deletion
import filer.fields.file
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('filer', '0018_alter_file_options'),
        ('task', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='name')),
                ('output_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('structured', 'Structured'), ('video', 'Video'), ('voice', 'Voice')], default='text', max_length=100, verbose_name='output type')),
                ('schema', models.CharField(blank=True, choices=[('multi_scene', 'Multi Scene Storyboard'), ('scene', 'Single Scene Storyboard')], max_length=100, null=True, verbose_name='schema')),
                ('agent_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agent.agentmodel', verbose_name='agent model')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='name')),
                ('api_key', models.TextField(blank=True, null=True, verbose_name='api key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='credits')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('google_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to='agent.googleapikey', verbose_name='google api key')),
            ],
            options={
                'verbose_name': 'AI User Profile',
                'verbose_name_plural': 'AI User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('input_text', models.TextField(blank=True, verbose_name='input text')),
                ('output_text', models.TextField(blank=True, verbose_name='output text')),
                ('target_field', models.CharField(blank=True, max_length=100, verbose_name='target field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_history', to='agent.agent', verbose_name='agent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('output_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_files', to='filer.file', verbose_name='output file')),
                ('output_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_images', to=settings.FILER_IMAGE_MODEL, verbose_name='output image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_messages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='name')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('refine', 'Refine'), ('video_image', 'Video'), ('video_first_last', 'Video First Last'), ('comic', 'Comic'), ('writer', 'Writer'), ('character', 'Character'), ('refine_prompt', 'Refine Prompt'), ('generate_scene', 'Sync Scene')], default='general', max_length=100)),
                ('content_types', models.ManyToManyField(blank=True, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='instructions',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agent.prompt', verbose_name='instructions'),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tokens', models.PositiveIntegerField(default=0, verbose_name='tokens')),
                ('json_report', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='agent.agent', verbose_name='agent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='task.task', verbose_name='task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
