# Generated by Django 5.2.10 on 2026-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='output_type',
            field=models.CharField(choices=[('text', 'Text'), ('structured', 'Structured'), ('image', 'Image')], default='text', max_length=100),
        ),
    ]
