# Generated by Django 6.0.3 on 2026-06-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
        migrations.AlterModelOptions(
            name='agentmodel',
            options={'verbose_name': 'agent model', 'verbose_name_plural': 'agent models'},
        ),
        migrations.AlterModelOptions(
            name='googleapikey',
            options={'verbose_name': 'google api key', 'verbose_name_plural': 'google api keys'},
        ),
        migrations.AlterModelOptions(
            name='googlevoice',
            options={'verbose_name': 'google voice', 'verbose_name_plural': 'google voices'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'verbose_name': 'prompt', 'verbose_name_plural': 'prompts'},
        ),
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'verbose_name': 'token usage', 'verbose_name_plural': 'token usages'},
        ),
        migrations.AlterField(
            model_name='googlevoice',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('refine', 'Refine'), ('video_image', 'Video'), ('video_first_last', 'Video First Last'), ('comic', 'Comic'), ('writer', 'Writer'), ('character', 'Character'), ('refine_prompt', 'Refine Prompt'), ('generate_scene', 'Sync Scene')], default='general', max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='content_types',
            field=models.ManyToManyField(blank=True, to='contenttypes.contenttype', verbose_name='content types'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(blank=True, null=True, verbose_name='prompt'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='json_report',
            field=models.JSONField(blank=True, null=True, verbose_name='json report'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
