# Generated by Django 5.2.10 on 2026-01-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentanswer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='output_type',
        ),
    ]
