# Generated by Django 6.0.3 on 2026-06-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_tokenusage_content_type_tokenusage_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='input_text',
        ),
        migrations.AddField(
            model_name='message',
            name='input_data',
            field=models.JSONField(blank=True, default=list, verbose_name='input data'),
        ),
    ]
