# Generated by Django 6.0.3 on 2026-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_message_input_text_message_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='is global'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
