# Generated by Django 5.2.10 on 2026-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_agent_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='output_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('structured', 'Structured')], default='text', max_length=100),
        ),
    ]
