# Generated by Django 5.2.10 on 2026-01-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agent_output_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentanswer',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
