# Generated by Django 6.0.3 on 2026-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_prompt_is_global_prompt_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleapikey',
            name='vertex',
            field=models.BooleanField(default=False, verbose_name='vertex'),
        ),
    ]
