# Generated by Django 6.0.3 on 2026-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_googleapikey_vertex'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleapikey',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='project'),
        ),
    ]
