# Generated by Django 5.2.10 on 2026-01-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_agentanswer_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprompt',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
