# Generated by Django 6.0.3 on 2026-07-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_googleapikey_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleapikey',
            name='vertex',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_model_enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_agents', to='agent.agentmodel', verbose_name='agent model'),
        ),
        migrations.AddField(
            model_name='googleapikey',
            name='enterprise',
            field=models.BooleanField(default=False, verbose_name='enterprise'),
        ),
    ]
