# Generated by Django 6.0.3 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_remove_googleapikey_vertex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='output_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('structured', 'Structured'), ('video', 'Video'), ('image_omni_video', 'Image Omni Video'), ('voice', 'Voice')], default='text', max_length=100, verbose_name='output type'),
        ),
    ]
