# Generated by Django 5.2.10 on 2026-03-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_agentprompt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='output_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('structured', 'Structured'), ('video', 'Video')], default='text', max_length=100),
        ),
    ]
