# Generated by Django 5.2.10 on 2026-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_agenttokenusage_usercredits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='general', max_length=100)),
            ],
        ),
    ]
