# Generated by Django 5.2.10 on 2026-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprompt',
            name='context',
        ),
        migrations.RemoveField(
            model_name='agentprompt',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentprompt',
            name='image',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('refine', 'Refine'), ('video_image', 'Video'), ('video_first_last', 'Video First Last'), ('comic', 'Comic')], default='general', max_length=100),
        ),
        migrations.DeleteModel(
            name='AgentAnswer',
        ),
        migrations.DeleteModel(
            name='AgentContext',
        ),
        migrations.DeleteModel(
            name='AgentPrompt',
        ),
    ]
