# Generated by Django 6.0.3 on 2026-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_remove_agentprompt_context_remove_agentprompt_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='output_type',
            field=models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('structured', 'Structured'), ('video', 'Video'), ('voice', 'Voice')], default='text', max_length=100),
        ),
    ]
