# Generated by Django 6.0.3 on 2026-05-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_alter_prompt_category_chatmessage'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='prompt',
        ),
        migrations.AddField(
            model_name='agent',
            name='instructions',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agent.prompt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('refine', 'Refine'), ('video_image', 'Video'), ('video_first_last', 'Video First Last'), ('comic', 'Comic'), ('writer', 'Writer'), ('character', 'Character'), ('refine_prompt', 'Refine Prompt')], default='general', max_length=100),
        ),
    ]
