# Generated by Django 6.0.4 on 2026-05-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_agentprofile_options'),
        ('agent', '0019_remove_agent_prompt_agent_instructions_and_more'),
    ]

    operations = [
    ]
