# Generated by Django 6.0.4 on 2026-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_merge_20260508_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('multi_scene', 'Multi Scene Storyboard')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('refine', 'Refine'), ('video_image', 'Video'), ('video_first_last', 'Video First Last'), ('comic', 'Comic'), ('writer', 'Writer'), ('character', 'Character'), ('refine_prompt', 'Refine Prompt'), ('generate_scene', 'Sync Scene')], default='general', max_length=100),
        ),
    ]
