# Generated by Django 6.0.3 on 2026-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_alter_prompt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='structured_schema',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
