# Generated by Django 6.0.3 on 2026-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_agent_structured_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='structured_schema',
            field=models.CharField(blank=True, choices=[('multi_scene', 'Multi Scene Storyboard')], max_length=100, null=True),
        ),
    ]
