# Generated by Django 6.0.3 on 2026-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_messagepart_content_type_messagepart_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('outwithmsg', 'Output With Message'), ('create_instructions', 'Create Instructions'), ('symbols', 'Symbols')], max_length=100, null=True, verbose_name='schema'),
        ),
    ]
