# Generated by Django 6.0.3 on 2026-05-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_alter_agent_structured_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='structured_schema',
            new_name='schema',
        ),
    ]
