# Generated by Django 6.0.3 on 2026-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_alter_agent_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptcategory',
            name='slug',
            field=models.SlugField(default='slug', max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
