# Generated by Django 6.0.3 on 2026-09-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0024_alter_promptcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('outwithmsg', 'Output With Message'), ('create_instructions', 'Create Instructions'), ('symbols', 'Symbols'), ('instances', 'Strategy Instances'), ('optimize', 'Optimize Strategy Instance')], max_length=100, null=True, verbose_name='schema'),
        ),
    ]
