# Generated by Django 6.0.3 on 2026-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0025_alter_agent_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('multiscene', 'Multi Scene Storyboard'), ('scene', 'Single Scene Storyboard'), ('outwithmsg', 'Output With Message'), ('create_instructions', 'Create Instructions'), ('story_scenes', 'Story Scenes'), ('assets', 'Assets'), ('symbols', 'Symbols'), ('instances', 'Strategy Instances'), ('translation', 'Scene Translation'), ('optimize', 'Optimize Strategy Instance')], max_length=100, null=True, verbose_name='schema'),
        ),
    ]
