# Generated by Django 6.0.3 on 2026-05-29 21:07

import django.db.models.deletion
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_message_user_delete_chatmessage'),
        ('filer', '0018_alter_file_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='prompt_sample',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='sample_text',
            field=models.TextField(blank=True, default='Hello, this is a sample voice. 1, 2, 3. Change me and add a sample prompt for better results. Add audio effects for more interesting voices!', null=True),
        ),
        migrations.AddField(
            model_name='voice',
            name='voice',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='filer.file'),
        ),
    ]
