# Generated by Django 6.0.3 on 2026-05-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0027_voice_prompt_voice_prompt_sample_voice_sample_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='voice',
        ),
    ]
