# Generated by Django 6.0.3 on 2026-05-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_remove_voice_voice'),
        ('scene', '0064_voice_alter_character_voice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
