# Generated by Django 6.0.3 on 2026-05-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0029_delete_voice'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='content_type',
        ),
        migrations.AddField(
            model_name='prompt',
            name='content_types',
            field=models.ManyToManyField(blank=True, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='schema',
            field=models.CharField(blank=True, choices=[('multi_scene', 'Multi Scene Storyboard'), ('scene', 'Single Scene Storyboard')], max_length=100, null=True),
        ),
    ]
