# Generated by Django 6.0.3 on 2026-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0030_remove_prompt_content_type_prompt_content_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
