# Generated by Django 6.0.3 on 2026-06-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_agent_schema_alter_prompt_category'),
        ('agent', '0031_googlevoice'),
    ]

    operations = [
    ]
