# Generated by Django 3.1.4 on 2020-12-28 20:25

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('is_core', '0002_auto_20201228_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketfile',
            name='hyper_file',
        ),
        migrations.AddField(
            model_name='audio',
            name='bucket_file',
            field=models.ForeignKey(blank=True, help_text='In distributed storage. Typical generated files.', null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.bucketfile'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, help_text='In server storage.', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.bucketfile'),
        ),
        migrations.DeleteModel(
            name='HyperFile',
        ),
    ]
