# Generated by Django 3.1.4 on 2020-12-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0003_auto_20201228_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.audioanalysis'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.speaker'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=models.ManyToManyField(blank=True, to='is_core.Tag'),
        ),
    ]
