# Generated by Django 3.1.4 on 2020-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0004_auto_20201228_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='generator',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='audios',
            field=models.ManyToManyField(through='is_core.TutorialAudio', to='is_core.Audio'),
        ),
    ]
