# Generated by Django 3.1.4 on 2020-12-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('is_core', '0005_auto_20201229_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.PositiveIntegerField()),
                ('obj_id', models.PositiveIntegerField()),
                ('thr_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Error'), (4, 'Holding')], default=0)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('task_type', models.IntegerField(choices=[('analysis', 'Analysis'), ('audio_gen', 'Synthesys'), ('video_gen', 'Video')], default=0)),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.task')),
                ('obj_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='contenttypes.contenttype')),
                ('subject_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='contenttypes.contenttype')),
                ('thr_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thr', to='contenttypes.contenttype')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='itask',
            name='depend_on',
        ),
        migrations.RemoveField(
            model_name='itask',
            name='obj_ct',
        ),
        migrations.RemoveField(
            model_name='itask',
            name='subject_ct',
        ),
        migrations.RemoveField(
            model_name='itask',
            name='thr_ct',
        ),
        migrations.RemoveField(
            model_name='itask',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='bucket_file',
        ),
        migrations.RemoveField(
            model_name='text',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='text',
            name='categories',
            field=models.ManyToManyField(blank=True, to='is_core.Category'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='categories',
            field=models.ManyToManyField(blank=True, to='is_core.Category'),
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.DeleteModel(
            name='BucketFile',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.task'),
        ),
        migrations.DeleteModel(
            name='ITask',
        ),
    ]
