# Generated by Django 3.1.4 on 2020-12-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0006_auto_20201230_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Analysis'), ('audio_gen', 'Synthesys'), ('video_gen', 'Video')], default=0),
        ),
    ]
