# Generated by Django 3.1.4 on 2020-12-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0009_auto_20201230_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField()),
                ('preset_type', models.SlugField(choices=[('analysis', 'Audio Analysis'), ('speaker', 'Artificial Speaker'), ('video_maker', 'Video Maker')])),
                ('system_default', models.BooleanField(default=False, verbose_name='Default')),
                ('preset', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorialgenerator',
            name='audio_generator',
        ),
        migrations.RemoveField(
            model_name='tutorialgenerator',
            name='video_generator',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analysis'), ('speaker', 'Artificial Speaker'), ('video_maker', 'Video Maker')]),
        ),
        migrations.DeleteModel(
            name='AudioGenerator',
        ),
        migrations.DeleteModel(
            name='TutorialGenerator',
        ),
        migrations.DeleteModel(
            name='VideoGenerator',
        ),
    ]
