# Generated by Django 3.1.4 on 2021-01-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0010_auto_20201230_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.language'),
        ),
    ]
