# Generated by Django 3.1.5 on 2021-01-07 11:14

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('is_core', '0012_auto_20210102_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.text'),
        ),
        migrations.AddField(
            model_name='audioanalysis',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('video', 'Video Maker'), ('video_upload', 'Video Uploadr')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('video', 'Video Maker'), ('video_upload', 'Video Uploadr')]),
        ),
    ]
