# Generated by Django 3.1.5 on 2021-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0013_auto_20210107_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='tutorialaudio',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='audio',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
