# Generated by Django 3.1.5 on 2021-01-11 11:05

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('is_core', '0014_auto_20210108_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='UVideo',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='uploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.uvideo'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader')]),
        ),
    ]
