# Generated by Django 3.1.5 on 2021-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0016_tasklog_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', '-modified']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dependent',
            new_name='next',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Started'), (4, 'Success'), (5, 'Error'), (3, 'Holding')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple')]),
        ),
    ]
