# Generated by Django 3.1.5 on 2021-01-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0017_auto_20210113_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1023, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=1023, verbose_name='Category')),
                ('keywords', models.CharField(help_text='Comma separated', max_length=1023, verbose_name='Keywords')),
                ('privacyStatus', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=1023, verbose_name='PrivacyStatus')),
                ('url', models.URLField(verbose_name='Video Url')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Started'), (4, 'Success'), (5, 'Error'), (3, 'Holding')], default=1),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='uploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.video'),
        ),
        migrations.DeleteModel(
            name='UVideo',
        ),
    ]
