# Generated by Django 3.1.5 on 2021-01-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0019_auto_20210115_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='external_id',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
