# Generated by Django 3.1.5 on 2021-01-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0022_auto_20210121_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='video',
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='is_core.text'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
