# Generated by Django 3.1.5 on 2021-01-23 21:38

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('is_core', '0024_auto_20210123_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file'),
        ),
    ]
