# Generated by Django 3.1.5 on 2021-01-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0027_auto_20210124_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='is_core.text'),
        ),
    ]
