# Generated by Django 3.1.5 on 2021-01-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0029_playlist_playlisttutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_target',
            field=models.BooleanField(default=False, verbose_name='Is Global Target'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='is_core.language'),
            preserve_default=False,
        ),
    ]
