# Generated by Django 3.1.5 on 2021-01-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0030_auto_20210127_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='texts',
            field=models.ManyToManyField(blank=True, to='is_core.Text'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tutorials',
            field=models.ManyToManyField(blank=True, through='is_core.PlaylistTutorial', to='is_core.Tutorial'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_target',
            field=models.BooleanField(default=False, verbose_name='Global Target'),
        ),
        migrations.AlterField(
            model_name='playlisttutorial',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is_core.playlist'),
        ),
    ]
