# Generated by Django 3.1.5 on 2021-01-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0031_auto_20210128_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='is_core.language'),
        ),
    ]
