# Generated by Django 3.1.5 on 2021-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0033_auto_20210510_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='external_id',
            new_name='youtube_id',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='texts',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='tutorials',
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='youtube_id',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='is_core.Playlist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'Youtube Playlist Playlist Create')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'Youtube Playlist Playlist Create')]),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=1023, verbose_name='Tutorial Name'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Youtube Title'),
        ),
        migrations.DeleteModel(
            name='PlaylistTutorial',
        ),
    ]
