# Generated by Django 3.1.5 on 2021-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0034_auto_20210830_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='is_core.Playlist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'Youtube Playlist Create'), ('playlist_item_create', 'Youtube Playlist Item Create')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'Youtube Playlist Create'), ('playlist_item_create', 'Youtube Playlist Item Create')]),
        ),
    ]
