# Generated by Django 3.1.5 on 2022-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is_core', '0035_auto_20210831_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'YouTube Playlist Create'), ('playlist_item_create', 'YouTube Playlist Item Create')]),
        ),
        migrations.AlterField(
            model_name='taskpreset',
            name='preset_type',
            field=models.SlugField(choices=[('analysis', 'Audio Analyser'), ('speaker', 'Artificial Speaker'), ('joiner', 'Video Joiner'), ('video_tutorial', 'Video Tutorial'), ('video', 'Video Maker'), ('video_upload', 'Video Uploader'), ('tutorial_simple', 'Tutorial Creator Simple'), ('playlist_create', 'YouTube Playlist Create'), ('playlist_item_create', 'YouTube Playlist Item Create')]),
        ),
    ]
