# Generated by Django 6.0.3 on 2026-05-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0001_initial'),
        ('scene', '0047_alter_storyprofile_enable_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Auto create participants from this group, it happens only when the session is saved for the first time', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.storygroup'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='prompt',
            field=models.TextField(blank=True, default='#Location\n#Characters\n#Actions\n', null=True),
        ),
    ]
