# Generated by Django 6.0.3 on 2026-05-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0003_contactrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Script', 'verbose_name_plural': 'Scripts'},
        ),
    ]
