# Generated by Django 6.0.3 on 2026-05-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0004_alter_session_options'),
        ('scene', '0051_alter_action_action_alter_background_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scene.story'),
        ),
        migrations.AddField(
            model_name='turn',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scene.scene'),
        ),
    ]
