# Generated by Django 6.0.3 on 2026-05-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0005_session_scene_turn_scene'),
        ('scene', '0051_alter_action_action_alter_background_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scene.story'),
        ),
    ]
