# Generated by Django 6.0.3 on 2026-05-20 15:10

import agent.models
import brainstorm.mixins
import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_agent_structured_schema'),
        ('brainstorm', '0006_session_story'),
        ('scene', '0051_alter_action_action_alter_background_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='session',
            name='group',
        ),
        migrations.RemoveField(
            model_name='session',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='session',
            name='story',
        ),
        migrations.RemoveField(
            model_name='session',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='session',
        ),
        migrations.RemoveField(
            model_name='nudge',
            name='session',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='scene',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, brainstorm.mixins.UserCreatorMixin),
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='When time comes give it a name to remember it by!', max_length=100, null=True)),
                ('state', models.CharField(choices=[('scene', 'Scene'), ('plot', 'Plots'), ('finished', 'Finished')], default='scene', max_length=100)),
                ('group', models.ForeignKey(blank=True, help_text='Auto create authors from this group, it happens only when the script is saved for the first time', null=True, on_delete=django.db.models.deletion.CASCADE, to='scene.storygroup')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scene.story')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='scene.story')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brainstorm.theme')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('scene', 'Scene'), ('plot', 'Plot'), ('help', 'Help')], default='scene', max_length=100)),
                ('prompt', models.TextField(blank=True, default='#Location\n#Characters\n#Actions\n', null=True)),
                ('prompt_refine', models.TextField(blank=True, null=True)),
                ('pass_turn', models.BooleanField(default=False, help_text='If true, the turn will be passed to the next player')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='brainstorm.author')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scene.scene')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='brainstorm.script')),
            ],
            bases=(models.Model, task.models.TaskHolder, agent.models.GetContentsMixin),
        ),
        migrations.AddField(
            model_name='author',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='brainstorm.script'),
        ),
        migrations.AddField(
            model_name='nudge',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='brainstorm.script'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Turn',
        ),
    ]
