# Generated by Django 6.0.3 on 2026-05-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0007_remove_turn_participant_remove_session_group_and_more'),
        ('scene', '0052_remove_action_extras_action_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='scene',
        ),
        migrations.AlterField(
            model_name='script',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='scene.story'),
        ),
    ]
