# Generated by Django 6.0.3 on 2026-05-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0008_remove_script_scene_alter_script_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='prompt',
            field=models.TextField(blank=True, default='#Location\n#Cast\n#Props\n#Actions\n', null=True),
        ),
    ]
