# Generated by Django 6.0.3 on 2026-05-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstorm', '0009_alter_contribution_prompt'),
        ('scene', '0054_action_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='state',
        ),
        migrations.AddField(
            model_name='script',
            name='render_type',
            field=models.CharField(choices=[('film', 'Film'), ('graphic_novel', 'Graphic Novel'), ('animatic', 'Animatic')], default='animatic', help_text='The default render format for stories generated from this script.', max_length=50),
        ),
        migrations.AddField(
            model_name='script',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='scene.style'),
        ),
    ]
